-- Add more professional lesson articles for remaining courses
INSERT INTO course_articles (module_id, title, content, excerpt, category, order_index, reading_time_minutes, is_published, tags)
VALUES
('working-capital-module-1-beginner', 'Working Capital Fundamentals: Managing Business Cash Flow', 
'<h2>Understanding Working Capital</h2><p>Working capital represents the difference between a company''s current assets and current liabilities. It is the lifeblood of daily business operations.</p><h3>The Working Capital Cycle</h3><p>Every business operates on a working capital cycle: purchasing inventory, converting it to sales, collecting receivables, and paying suppliers.</p><h3>Key Components</h3><ul><li><strong>Current Assets:</strong> Cash, accounts receivable, inventory</li><li><strong>Current Liabilities:</strong> Accounts payable, short-term debt</li><li><strong>Net Working Capital:</strong> The difference indicating operational liquidity</li></ul><h3>Working Capital Ratios</h3><p>The current ratio should typically be between 1.2 and 2.0. Below 1.0 indicates liquidity problems; above 3.0 may suggest inefficient asset utilization.</p>',
'Learn the fundamentals of working capital management.', 'Working Capital', 1, 12, true, ARRAY['working-capital', 'cash-flow']),

('invoice-factoring-module-1-beginner', 'Invoice Factoring: Converting Receivables to Cash', 
'<h2>What is Invoice Factoring?</h2><p>Invoice factoring is a financial transaction where a business sells its accounts receivable to a third party at a discount for immediate cash flow.</p><h3>How Factoring Works</h3><ol><li>Business delivers goods/services and invoices the customer</li><li>Business sells the invoice to a factoring company</li><li>Factor advances 80-95% of the invoice value immediately</li><li>Customer pays the factor directly</li><li>Factor remits the remaining balance minus fees</li></ol><h3>Cost Structure</h3><p>Factoring fees typically range from 1-5% per month. While more expensive than traditional lending, the speed and reduced collection burden often justify the cost.</p>',
'Understand how invoice factoring works and when to use it.', 'Invoice Factoring', 1, 10, true, ARRAY['factoring', 'accounts-receivable']),

('merchant-cash-advances-module-1-beginner', 'Merchant Cash Advances: Structure and Applications', 
'<h2>Understanding MCAs</h2><p>A Merchant Cash Advance provides businesses with upfront capital in exchange for a percentage of future credit card sales. It is technically a purchase of future receivables.</p><h3>Key Terms</h3><ul><li><strong>Factor Rate:</strong> Typically 1.1 to 1.5</li><li><strong>Holdback Percentage:</strong> 10-20% of daily sales</li><li><strong>Retrieval Rate:</strong> Percentage of daily revenue withheld</li></ul><h3>Ideal Candidates</h3><p>MCAs work best for businesses with strong, consistent credit card sales—restaurants, retail stores, and service businesses. They provide fast funding but at higher effective cost.</p>',
'Learn the structure, costs, and use cases for merchant cash advances.', 'Merchant Cash Advances', 1, 11, true, ARRAY['mca', 'alternative-lending']),

('franchise-financing-module-1-beginner', 'Franchise Financing: Funding Your Franchise Investment', 
'<h2>Franchise Financing Overview</h2><p>Franchise financing encompasses various funding methods for purchasing or expanding a franchise business. The franchise model offers unique advantages for lenders due to proven business systems.</p><h3>Financing Components</h3><ul><li><strong>Franchise Fee:</strong> $20,000-$100,000+</li><li><strong>Buildout Costs:</strong> Construction, equipment, signage</li><li><strong>Working Capital:</strong> Operating funds for first 6-12 months</li><li><strong>Real Estate:</strong> Purchase or lease costs</li></ul><h3>SBA Franchise Directory</h3><p>The SBA maintains an approved Franchise Directory, streamlining the lending process for listed franchises.</p>',
'Explore financing options for franchise businesses.', 'Franchise Financing', 1, 13, true, ARRAY['franchise', 'sba']),

('healthcare-financing-module-1-beginner', 'Healthcare Practice Financing: Specialized Solutions', 
'<h2>Healthcare Financing Fundamentals</h2><p>Healthcare practice financing serves medical, dental, veterinary, and specialty practices with distinctive cash flow patterns driven by insurance reimbursements.</p><h3>Types of Healthcare Financing</h3><ul><li><strong>Practice Acquisition Loans:</strong> Buying an existing practice</li><li><strong>Equipment Financing:</strong> Medical/dental equipment</li><li><strong>Tenant Improvement:</strong> Office buildout and renovation</li><li><strong>Working Capital Lines:</strong> Bridge insurance reimbursement gaps</li></ul><h3>Unique Lending Metrics</h3><p>Healthcare lending uses specialized metrics: collections rate, payer mix analysis, procedures per day, and revenue per patient visit.</p>',
'Learn about specialized financing for healthcare practices.', 'Healthcare Financing', 1, 14, true, ARRAY['healthcare', 'medical-practice']),

('asset-based-lending-module-1-beginner', 'Asset-Based Lending: Leveraging Business Assets', 
'<h2>ABL Explained</h2><p>Asset-Based Lending is business financing secured by collateral—accounts receivable, inventory, equipment, or real estate. Borrowing capacity is tied directly to pledged asset value.</p><h3>Borrowing Base Formula</h3><p>ABL uses a borrowing base: typically 80-85% of eligible receivables plus 50-65% of eligible inventory.</p><h3>ABL vs. Cash Flow Lending</h3><p>Cash flow lending relies on earnings; ABL focuses on collateral value, making it accessible to companies with strong assets but challenged credit profiles.</p>',
'Understand how asset-based lending works.', 'Asset-Based Lending', 1, 11, true, ARRAY['abl', 'collateral-lending']);
