
-- Batch 3: Remaining beginner modules 2-7 for Construction, Equipment, Working Capital, Invoice Factoring, MCA, Franchise, Healthcare, Restaurant, ABL, LOC + SBA 504/Express modules 2-7
INSERT INTO course_assessments (module_id, title, assessment_type, order_index, passing_score, is_required, max_attempts, time_limit_minutes, questions) VALUES

-- Construction Beginner 2-7
('construction-loans-module-2-beginner', 'Construction Product Structures Quiz', 'quiz', 1, 80, true, 3, 15, '[
  {"question": "What is a construction-to-permanent loan?", "type": "multiple-choice", "options": ["Two separate loans", "Single loan converting from construction to permanent at completion", "Only for residential", "Government program"], "correctAnswer": "Single loan converting from construction to permanent at completion", "explanation": "A single-close loan eliminates refinance risk and saves on closing costs.", "points": 15, "difficulty": "medium"},
  {"question": "What is a speculative (spec) construction loan?", "type": "multiple-choice", "options": ["A loan for renovations", "Construction without a committed buyer or tenant", "Government-backed construction", "A loan under $100K"], "correctAnswer": "Construction without a committed buyer or tenant", "explanation": "Spec loans carry higher risk since the developer builds without pre-sales or pre-leases.", "points": 15, "difficulty": "medium"},
  {"question": "What is the typical construction loan term?", "type": "multiple-choice", "options": ["6 months", "12-24 months", "5-10 years", "25-30 years"], "correctAnswer": "12-24 months", "explanation": "Construction loans typically run 12-24 months to cover the building phase.", "points": 10, "difficulty": "easy"},
  {"question": "What is a draw schedule?", "type": "multiple-choice", "options": ["Payment timeline", "Planned disbursement of funds tied to construction milestones", "Interest rate schedule", "Inspection calendar"], "correctAnswer": "Planned disbursement of funds tied to construction milestones", "explanation": "Draw schedules align fund releases with verified construction progress.", "points": 10, "difficulty": "easy"}
]'::jsonb),

('construction-loans-module-3-beginner', 'Construction Borrower Assessment Quiz', 'quiz', 1, 80, true, 3, 15, '[
  {"question": "What is the most important factor in evaluating a construction borrower?", "type": "multiple-choice", "options": ["Personal credit score only", "Track record of completing similar projects", "Total net worth", "Number of employees"], "correctAnswer": "Track record of completing similar projects", "explanation": "Experience with similar-scale projects is the strongest predictor of successful completion.", "points": 15, "difficulty": "medium"},
  {"question": "What is a completion guarantee?", "type": "multiple-choice", "options": ["Insurance policy", "Personal guarantee that the project will be finished on budget", "Government subsidy", "Contractor warranty"], "correctAnswer": "Personal guarantee that the project will be finished on budget", "explanation": "Sponsors personally guarantee they will complete the project even if costs exceed budget.", "points": 15, "difficulty": "medium"},
  {"question": "Why do lenders require a contractor qualification review?", "type": "multiple-choice", "options": ["Legal requirement", "To verify contractor experience, financial strength, and bonding", "To set the interest rate", "Only for government projects"], "correctAnswer": "To verify contractor experience, financial strength, and bonding", "explanation": "Contractor qualification ensures they can complete the project and handle cost overruns.", "points": 10, "difficulty": "easy"},
  {"question": "What is a performance bond?", "type": "multiple-choice", "options": ["Interest rate guarantee", "Third-party guarantee contractor will complete the project", "Construction insurance", "Permit deposit"], "correctAnswer": "Third-party guarantee contractor will complete the project", "explanation": "Performance bonds from surety companies guarantee project completion if the contractor defaults.", "points": 10, "difficulty": "easy"}
]'::jsonb),

('construction-loans-module-4-beginner', 'Construction Documentation Quiz', 'quiz', 1, 80, true, 3, 15, '[
  {"question": "What is an AIA contract?", "type": "multiple-choice", "options": ["Insurance agreement", "Standardized construction contract from American Institute of Architects", "Appraisal document", "Loan application"], "correctAnswer": "Standardized construction contract from American Institute of Architects", "explanation": "AIA contracts are industry-standard documents governing construction relationships.", "points": 10, "difficulty": "easy"},
  {"question": "What is a construction budget contingency?", "type": "multiple-choice", "options": ["Emergency fund for natural disasters", "Reserve for unexpected cost overruns (typically 5-10%)", "Contractor bonus pool", "Insurance deductible"], "correctAnswer": "Reserve for unexpected cost overruns (typically 5-10%)", "explanation": "Contingency reserves (5-10% of hard costs) cover unforeseen expenses during construction.", "points": 15, "difficulty": "medium"},
  {"question": "What does a title update during construction verify?", "type": "multiple-choice", "options": ["Contractor license", "No new liens have been filed against the property", "Building progress", "Insurance coverage"], "correctAnswer": "No new liens have been filed against the property", "explanation": "Title updates before each draw ensure no mechanics liens or other encumbrances exist.", "points": 15, "difficulty": "medium"},
  {"question": "What is a lien waiver?", "type": "multiple-choice", "options": ["Insurance document", "Contractor statement waiving right to file a lien for paid work", "Permit application", "Zoning variance"], "correctAnswer": "Contractor statement waiving right to file a lien for paid work", "explanation": "Lien waivers confirm subcontractors have been paid and will not file liens.", "points": 10, "difficulty": "easy"}
]'::jsonb),

('construction-loans-module-5-beginner', 'Construction Financial Analysis Quiz', 'quiz', 1, 80, true, 3, 15, '[
  {"question": "How do you calculate construction loan interest during the build phase?", "type": "multiple-choice", "options": ["On the full loan amount from day one", "On the outstanding drawn balance only", "Flat monthly fee", "No interest during construction"], "correctAnswer": "On the outstanding drawn balance only", "explanation": "Interest accrues only on funds actually disbursed, increasing as draws are made.", "points": 10, "difficulty": "easy"},
  {"question": "What is the total project cost in construction lending?", "type": "multiple-choice", "options": ["Land cost only", "Hard costs + soft costs + land + financing costs + contingency", "Construction contract amount", "Appraised value"], "correctAnswer": "Hard costs + soft costs + land + financing costs + contingency", "explanation": "Total project cost includes all development expenses from land acquisition through completion.", "points": 15, "difficulty": "medium"},
  {"question": "What is a feasibility study?", "type": "multiple-choice", "options": ["Building inspection", "Analysis of whether the project is financially viable", "Environmental test", "Soil analysis"], "correctAnswer": "Analysis of whether the project is financially viable", "explanation": "Feasibility studies assess market demand, projected costs, revenues, and return on investment.", "points": 15, "difficulty": "medium"},
  {"question": "What is profit margin in construction development?", "type": "multiple-choice", "options": ["Interest rate spread", "Difference between total cost and projected completed value", "Contractor markup", "Fee income"], "correctAnswer": "Difference between total cost and projected completed value", "explanation": "Development profit = completed value minus total project cost, expressed as a percentage.", "points": 10, "difficulty": "easy"}
]'::jsonb),

('construction-loans-module-6-beginner', 'Construction Underwriting Quiz', 'quiz', 1, 80, true, 3, 15, '[
  {"question": "What is the as-completed appraisal?", "type": "multiple-choice", "options": ["Current land value", "Projected value of the property upon completion", "Historical property value", "Insurance replacement cost"], "correctAnswer": "Projected value of the property upon completion", "explanation": "As-completed appraisals estimate market value assuming the project is finished as planned.", "points": 10, "difficulty": "easy"},
  {"question": "What is an as-stabilized value?", "type": "multiple-choice", "options": ["Value during construction", "Projected value after achieving target occupancy", "Liquidation value", "Land-only value"], "correctAnswer": "Projected value after achieving target occupancy", "explanation": "As-stabilized value assumes the property reaches market occupancy and generates normal NOI.", "points": 15, "difficulty": "medium"},
  {"question": "What is the key risk in construction lending vs permanent lending?", "type": "multiple-choice", "options": ["Interest rate risk", "Completion risk - project may not be finished on time/budget", "Tenant risk", "Inflation risk"], "correctAnswer": "Completion risk - project may not be finished on time/budget", "explanation": "The primary construction risk is that the project may not be completed as planned.", "points": 15, "difficulty": "medium"},
  {"question": "What is a cost-to-complete analysis?", "type": "multiple-choice", "options": ["Historical spending review", "Estimate of remaining funds needed to finish the project", "Final accounting report", "Tax calculation"], "correctAnswer": "Estimate of remaining funds needed to finish the project", "explanation": "Cost-to-complete ensures remaining loan funds are sufficient to finish construction.", "points": 10, "difficulty": "easy"}
]'::jsonb),

('construction-loans-module-7-beginner', 'Construction Closing & Management Quiz', 'quiz', 1, 80, true, 3, 15, '[
  {"question": "What is a certificate of occupancy?", "type": "multiple-choice", "options": ["Insurance certificate", "Government approval that building meets codes and is safe to occupy", "Tenant lease agreement", "Contractor completion form"], "correctAnswer": "Government approval that building meets codes and is safe to occupy", "explanation": "A CO certifies the building complies with all codes and can be legally occupied.", "points": 10, "difficulty": "easy"},
  {"question": "What is substantial completion?", "type": "multiple-choice", "options": ["100% of work done", "Project sufficiently complete for its intended use", "First phase complete", "Foundation poured"], "correctAnswer": "Project sufficiently complete for its intended use", "explanation": "Substantial completion means the project can be used for its intended purpose despite minor punch list items.", "points": 15, "difficulty": "medium"},
  {"question": "What is a punch list?", "type": "multiple-choice", "options": ["Construction schedule", "List of minor items to complete after substantial completion", "Inspection checklist", "Budget summary"], "correctAnswer": "List of minor items to complete after substantial completion", "explanation": "Punch lists document remaining minor work items that must be resolved before final completion.", "points": 10, "difficulty": "easy"},
  {"question": "What happens if a construction loan matures before project completion?", "type": "multiple-choice", "options": ["Automatic extension", "Lender may extend, restructure, or declare default", "Government covers remaining costs", "Contractor takes over the loan"], "correctAnswer": "Lender may extend, restructure, or declare default", "explanation": "Options include negotiated extensions (with fees), restructuring terms, or enforcement actions.", "points": 15, "difficulty": "medium"}
]'::jsonb),

-- Equipment Beginner 2-7
('equipment-financing-module-2-beginner', 'Equipment Products & Structures Quiz', 'quiz', 1, 80, true, 3, 15, '[
  {"question": "What is an equipment lease vs a loan?", "type": "multiple-choice", "options": ["No difference", "Lease provides use without ownership; loan transfers ownership", "Leases are always cheaper", "Loans are only for used equipment"], "correctAnswer": "Lease provides use without ownership; loan transfers ownership", "explanation": "Leases provide asset use; loans provide ownership with the equipment as collateral.", "points": 10, "difficulty": "easy"},
  {"question": "What is a $1 buyout lease?", "type": "multiple-choice", "options": ["A free equipment giveaway", "Capital lease where lessee buys equipment for $1 at end", "Short-term rental", "Government subsidy"], "correctAnswer": "Capital lease where lessee buys equipment for $1 at end", "explanation": "$1 buyout leases function like loans - the lessee owns the equipment at term end.", "points": 15, "difficulty": "medium"},
  {"question": "What is a fair market value (FMV) lease?", "type": "multiple-choice", "options": ["Equipment given at no cost", "Lessee can purchase at FMV at lease end or return it", "A government program", "Only for new equipment"], "correctAnswer": "Lessee can purchase at FMV at lease end or return it", "explanation": "FMV leases offer flexibility - lower payments but uncertainty on end-of-term cost.", "points": 15, "difficulty": "medium"},
  {"question": "What is the typical equipment loan term?", "type": "multiple-choice", "options": ["1-2 years", "3-7 years", "10-15 years", "25 years"], "correctAnswer": "3-7 years", "explanation": "Most equipment loans run 3-7 years, matching the asset useful life.", "points": 10, "difficulty": "easy"}
]'::jsonb),

('equipment-financing-module-3-beginner', 'Equipment Borrower Assessment Quiz', 'quiz', 1, 80, true, 3, 15, '[
  {"question": "What is the most important factor in equipment financing approval?", "type": "multiple-choice", "options": ["Equipment brand", "Business cash flow to service the debt", "Equipment color", "Building size"], "correctAnswer": "Business cash flow to service the debt", "explanation": "Cash flow determines the borrower ability to make payments regardless of equipment value.", "points": 10, "difficulty": "easy"},
  {"question": "What is the time-in-business requirement for most equipment lenders?", "type": "multiple-choice", "options": ["No requirement", "At least 2 years", "At least 10 years", "Must be a startup"], "correctAnswer": "At least 2 years", "explanation": "Most lenders require 2+ years of operating history to evaluate financial stability.", "points": 10, "difficulty": "easy"},
  {"question": "Why do lenders evaluate equipment condition and age?", "type": "multiple-choice", "options": ["For insurance purposes only", "To assess collateral value and remaining useful life", "Legal requirement", "To set the interest rate"], "correctAnswer": "To assess collateral value and remaining useful life", "explanation": "Equipment age and condition affect both collateral value and the appropriate loan term.", "points": 15, "difficulty": "medium"},
  {"question": "What is a vendor financing program?", "type": "multiple-choice", "options": ["Government subsidy", "Equipment manufacturer or dealer offers financing to buyers", "Employee purchase plan", "Charity program"], "correctAnswer": "Equipment manufacturer or dealer offers financing to buyers", "explanation": "Vendors partner with lenders to offer point-of-sale financing, simplifying the purchase.", "points": 15, "difficulty": "medium"}
]'::jsonb),

('equipment-financing-module-4-beginner', 'Equipment Documentation Quiz', 'quiz', 1, 80, true, 3, 15, '[
  {"question": "What document describes the specific equipment being financed?", "type": "multiple-choice", "options": ["UCC filing", "Equipment schedule or description", "Promissory note", "Personal guarantee"], "correctAnswer": "Equipment schedule or description", "explanation": "The equipment schedule details make, model, serial number, and specifications.", "points": 10, "difficulty": "easy"},
  {"question": "What is a blanket lien in equipment financing?", "type": "multiple-choice", "options": ["Lien on specific equipment only", "Lien covering all business assets including future acquisitions", "Insurance policy", "Tax lien"], "correctAnswer": "Lien covering all business assets including future acquisitions", "explanation": "Blanket liens secure the lender interest in all current and future business assets.", "points": 15, "difficulty": "medium"},
  {"question": "What is required for used equipment financing?", "type": "multiple-choice", "options": ["Nothing extra", "Equipment appraisal or valuation and condition report", "Only manufacturer approval", "New warranty required"], "correctAnswer": "Equipment appraisal or valuation and condition report", "explanation": "Used equipment requires independent valuation and condition assessment.", "points": 15, "difficulty": "medium"},
  {"question": "What is an equipment bill of sale?", "type": "multiple-choice", "options": ["Insurance document", "Legal document transferring ownership of equipment", "Maintenance record", "Warranty card"], "correctAnswer": "Legal document transferring ownership of equipment", "explanation": "The bill of sale documents the transfer of equipment ownership from seller to buyer.", "points": 10, "difficulty": "easy"}
]'::jsonb),

('equipment-financing-module-5-beginner', 'Equipment Financial Analysis Quiz', 'quiz', 1, 80, true, 3, 15, '[
  {"question": "How do you calculate the total cost of equipment ownership?", "type": "multiple-choice", "options": ["Purchase price only", "Purchase price + financing costs + maintenance + insurance - residual value", "Monthly payments × term", "Down payment only"], "correctAnswer": "Purchase price + financing costs + maintenance + insurance - residual value", "explanation": "Total cost of ownership includes all costs over the asset life minus end value.", "points": 15, "difficulty": "medium"},
  {"question": "What is ROI analysis for equipment purchases?", "type": "multiple-choice", "options": ["Revenue only", "Additional revenue or savings generated vs total cost of the equipment", "Interest rate comparison", "Tax benefit only"], "correctAnswer": "Additional revenue or savings generated vs total cost of the equipment", "explanation": "ROI measures whether the equipment generates enough return to justify the investment.", "points": 15, "difficulty": "medium"},
  {"question": "What depreciation method is most common for equipment?", "type": "multiple-choice", "options": ["No depreciation", "MACRS (Modified Accelerated Cost Recovery System)", "Straight-line only", "Sum of years digits"], "correctAnswer": "MACRS (Modified Accelerated Cost Recovery System)", "explanation": "MACRS is the standard tax depreciation method for business equipment in the US.", "points": 10, "difficulty": "easy"},
  {"question": "What is the payback period for equipment?", "type": "multiple-choice", "options": ["Loan term", "Time for the equipment to generate enough cash flow to cover its cost", "Warranty period", "Depreciation schedule"], "correctAnswer": "Time for the equipment to generate enough cash flow to cover its cost", "explanation": "Payback period measures how quickly the investment recoups its cost from operations.", "points": 10, "difficulty": "easy"}
]'::jsonb),

('equipment-financing-module-6-beginner', 'Equipment Underwriting Quiz', 'quiz', 1, 80, true, 3, 15, '[
  {"question": "What is the primary collateral in equipment financing?", "type": "multiple-choice", "options": ["Real estate", "The financed equipment itself", "Personal assets", "Accounts receivable"], "correctAnswer": "The financed equipment itself", "explanation": "The equipment being financed serves as the primary collateral for the loan.", "points": 10, "difficulty": "easy"},
  {"question": "What is orderly liquidation value (OLV)?", "type": "multiple-choice", "options": ["Retail price", "Value if sold in a reasonable timeframe (not forced sale)", "Scrap value", "Insurance replacement cost"], "correctAnswer": "Value if sold in a reasonable timeframe (not forced sale)", "explanation": "OLV represents expected proceeds from a sale conducted in an orderly manner.", "points": 15, "difficulty": "medium"},
  {"question": "Why do specialized equipment types receive lower advance rates?", "type": "multiple-choice", "options": ["They cost more", "Limited resale market makes liquidation harder", "They depreciate slower", "They require more maintenance"], "correctAnswer": "Limited resale market makes liquidation harder", "explanation": "Specialized equipment has fewer potential buyers, increasing liquidation risk.", "points": 15, "difficulty": "medium"},
  {"question": "What is cross-collateralization?", "type": "multiple-choice", "options": ["Insurance term", "Using collateral from one loan to secure another loan", "Equipment trade-in", "Multiple guarantors"], "correctAnswer": "Using collateral from one loan to secure another loan", "explanation": "Cross-collateralization strengthens the lender position by securing multiple obligations.", "points": 10, "difficulty": "easy"}
]'::jsonb),

('equipment-financing-module-7-beginner', 'Equipment Monitoring & Management Quiz', 'quiz', 1, 80, true, 3, 15, '[
  {"question": "What triggers an equipment loan default?", "type": "multiple-choice", "options": ["Equipment maintenance", "Missing payments, selling collateral, or insurance lapse", "Equipment upgrade", "Seasonal slowdown"], "correctAnswer": "Missing payments, selling collateral, or insurance lapse", "explanation": "Default events include payment delinquency, unauthorized disposition of collateral, or covenant violations.", "points": 15, "difficulty": "medium"},
  {"question": "What is equipment repossession?", "type": "multiple-choice", "options": ["Scheduled maintenance", "Lender taking possession of equipment after default", "Equipment upgrade", "Warranty claim"], "correctAnswer": "Lender taking possession of equipment after default", "explanation": "Upon default, the lender may exercise its security interest to repossess the equipment.", "points": 10, "difficulty": "easy"},
  {"question": "What is an equipment replacement reserve?", "type": "multiple-choice", "options": ["Insurance fund", "Funds set aside for replacing equipment at end of useful life", "Loan prepayment", "Tax escrow"], "correctAnswer": "Funds set aside for replacing equipment at end of useful life", "explanation": "Replacement reserves ensure the business can acquire new equipment when current assets wear out.", "points": 15, "difficulty": "medium"},
  {"question": "Why is equipment insurance important to lenders?", "type": "multiple-choice", "options": ["Legal requirement only", "Protects collateral value against damage, theft, or destruction", "Reduces interest rate", "Tax benefit"], "correctAnswer": "Protects collateral value against damage, theft, or destruction", "explanation": "Insurance ensures the lender collateral is protected; lapse is typically a default event.", "points": 10, "difficulty": "easy"}
]'::jsonb),

-- SBA 504 Beginner 2-7
('sba-504-module-2-beginner', 'SBA 504 Project Types Quiz', 'quiz', 1, 80, true, 3, 15, '[
  {"question": "What assets can be financed with a 504 loan?", "type": "multiple-choice", "options": ["Working capital and inventory", "Land, buildings, and major equipment", "Marketing expenses", "Employee salaries"], "correctAnswer": "Land, buildings, and major equipment", "explanation": "504 is for long-lived fixed assets: land, buildings, and equipment with 10+ year life.", "points": 10, "difficulty": "easy"},
  {"question": "Can 504 loans be used for debt refinancing?", "type": "multiple-choice", "options": ["Never", "Yes, under the 504 refinance program with conditions", "Only for SBA debt", "Only if originated before 2010"], "correctAnswer": "Yes, under the 504 refinance program with conditions", "explanation": "The 504 refinance program allows refinancing of qualifying existing debt.", "points": 15, "difficulty": "medium"},
  {"question": "What is the borrower equity requirement for special-purpose properties?", "type": "multiple-choice", "options": ["5%", "10%", "15%", "20%"], "correctAnswer": "15%", "explanation": "Special-purpose properties or startups require 15% equity (vs 10% standard).", "points": 15, "difficulty": "medium"},
  {"question": "What types of businesses cannot use 504?", "type": "multiple-choice", "options": ["Restaurants", "Nonprofits and passive real estate investors", "Manufacturing", "Healthcare practices"], "correctAnswer": "Nonprofits and passive real estate investors", "explanation": "504 is for for-profit businesses; nonprofits and passive investors are ineligible.", "points": 10, "difficulty": "easy"}
]'::jsonb),

('sba-504-module-3-beginner', 'SBA 504 Eligibility Quiz', 'quiz', 1, 80, true, 3, 15, '[
  {"question": "What is the tangible net worth limit for 504 eligibility?", "type": "multiple-choice", "options": ["$5 million", "$7.5 million", "$15 million", "$20 million"], "correctAnswer": "$15 million", "explanation": "Businesses must have tangible net worth under $15 million to qualify.", "points": 15, "difficulty": "medium"},
  {"question": "What is the average net income limit for 504?", "type": "multiple-choice", "options": ["$1 million", "$2.5 million", "$5 million", "$10 million"], "correctAnswer": "$5 million", "explanation": "Average net income (after taxes) must be under $5 million for the prior two years.", "points": 15, "difficulty": "medium"},
  {"question": "Must 504 borrowers occupy the property?", "type": "multiple-choice", "options": ["No occupancy required", "51% for existing buildings, 60% for new construction", "100% owner-occupied", "Any amount of occupancy"], "correctAnswer": "51% for existing buildings, 60% for new construction", "explanation": "Owner-occupancy requirements ensure the property serves the borrower business.", "points": 10, "difficulty": "easy"},
  {"question": "Can startups use 504 loans?", "type": "multiple-choice", "options": ["No", "Yes, but with higher equity (15%) and additional requirements", "Only after 5 years in business", "Only with SBA Express first"], "correctAnswer": "Yes, but with higher equity (15%) and additional requirements", "explanation": "Startups are eligible but must contribute 15% equity and demonstrate feasibility.", "points": 10, "difficulty": "easy"}
]'::jsonb),

('sba-504-module-4-beginner', 'SBA 504 Documentation Quiz', 'quiz', 1, 80, true, 3, 15, '[
  {"question": "Who originates the 504 loan application?", "type": "multiple-choice", "options": ["The borrower directly to SBA", "The CDC in partnership with the borrower", "The bank only", "An attorney"], "correctAnswer": "The CDC in partnership with the borrower", "explanation": "The CDC works with the borrower to prepare and submit the application to SBA.", "points": 10, "difficulty": "easy"},
  {"question": "What is SBA Form 1244?", "type": "multiple-choice", "options": ["Personal financial statement", "Application for 504 certification", "Environmental questionnaire", "Business plan template"], "correctAnswer": "Application for 504 certification", "explanation": "Form 1244 is the CDC application package submitted to SBA for 504 loan authorization.", "points": 15, "difficulty": "medium"},
  {"question": "What appraisal requirements apply to 504 loans?", "type": "multiple-choice", "options": ["No appraisal needed", "Independent FIRREA-compliant appraisal required", "Self-assessment allowed", "Only for loans over $1M"], "correctAnswer": "Independent FIRREA-compliant appraisal required", "explanation": "All 504 loans require an independent appraisal meeting FIRREA and USPAP standards.", "points": 15, "difficulty": "medium"},
  {"question": "What is the 504 interim loan?", "type": "multiple-choice", "options": ["Short-term personal loan", "Temporary financing until the CDC debenture is funded", "Emergency bridge loan", "SBA direct lending"], "correctAnswer": "Temporary financing until the CDC debenture is funded", "explanation": "The interim loan covers the CDC portion until the next debenture pool is sold.", "points": 10, "difficulty": "easy"}
]'::jsonb),

('sba-504-module-5-beginner', 'SBA 504 Financial Analysis Quiz', 'quiz', 1, 80, true, 3, 15, '[
  {"question": "What DSCR does SBA typically require for 504 loans?", "type": "multiple-choice", "options": ["0.90x", "1.0x", "1.15x", "1.50x"], "correctAnswer": "1.15x", "explanation": "SBA generally requires at least 1.15x DSCR for 504 loan approval.", "points": 10, "difficulty": "easy"},
  {"question": "How is the 504 interest rate determined?", "type": "multiple-choice", "options": ["Lender sets freely", "CDC debenture rate is tied to US Treasury rates at time of sale", "Fixed by SBA", "Based on borrower credit score"], "correctAnswer": "CDC debenture rate is tied to US Treasury rates at time of sale", "explanation": "The CDC debenture rate is pegged to comparable Treasury yields plus a spread.", "points": 15, "difficulty": "medium"},
  {"question": "What makes 504 more affordable than conventional CRE?", "type": "multiple-choice", "options": ["No down payment", "Lower equity, fixed long-term rate on CDC portion, no balloon", "No closing costs", "Government pays the interest"], "correctAnswer": "Lower equity, fixed long-term rate on CDC portion, no balloon", "explanation": "504 offers lower equity (10%), a below-market fixed rate for 20-25 years, and no balloon risk.", "points": 15, "difficulty": "medium"},
  {"question": "How are 504 fees structured?", "type": "multiple-choice", "options": ["No fees", "CDC processing fee + SBA guarantee fee + funding fee", "Bank fees only", "Annual maintenance fee only"], "correctAnswer": "CDC processing fee + SBA guarantee fee + funding fee", "explanation": "504 fees include CDC processing, SBA guarantee fee, and funding fee, typically rolled into the loan.", "points": 10, "difficulty": "easy"}
]'::jsonb),

('sba-504-module-6-beginner', 'SBA 504 Underwriting Quiz', 'quiz', 1, 80, true, 3, 15, '[
  {"question": "Who underwrites the 504 loan?", "type": "multiple-choice", "options": ["SBA only", "Both the bank (first mortgage) and CDC/SBA (debenture)", "The borrower", "An independent auditor"], "correctAnswer": "Both the bank (first mortgage) and CDC/SBA (debenture)", "explanation": "The bank underwrites its first mortgage portion; the CDC and SBA underwrite the debenture.", "points": 10, "difficulty": "easy"},
  {"question": "What is the bank first lien position in a 504 structure?", "type": "multiple-choice", "options": ["Second lien", "First lien on the project with 50% of project cost", "No lien", "Third lien"], "correctAnswer": "First lien on the project with 50% of project cost", "explanation": "The bank holds a first lien position covering approximately 50% of total project cost.", "points": 15, "difficulty": "medium"},
  {"question": "What community impact does SBA evaluate for 504?", "type": "multiple-choice", "options": ["None", "Job creation/retention and economic development goals", "Environmental impact only", "Cultural significance"], "correctAnswer": "Job creation/retention and economic development goals", "explanation": "SBA evaluates community development impact including jobs, tax base, and economic goals.", "points": 15, "difficulty": "medium"},
  {"question": "Can 504 loans be declined for collateral shortfall?", "type": "multiple-choice", "options": ["Yes, always", "The project itself must serve as adequate collateral", "Only if shortfall exceeds 50%", "Collateral is not considered"], "correctAnswer": "The project itself must serve as adequate collateral", "explanation": "The financed project (real estate/equipment) serves as primary collateral for both lender portions.", "points": 10, "difficulty": "easy"}
]'::jsonb),

('sba-504-module-7-beginner', 'SBA 504 Closing & Servicing Quiz', 'quiz', 1, 80, true, 3, 15, '[
  {"question": "What is the debenture funding timeline?", "type": "multiple-choice", "options": ["Immediate at closing", "Monthly pooling - typically 4-6 weeks after authorization", "Annual funding", "Quarterly"], "correctAnswer": "Monthly pooling - typically 4-6 weeks after authorization", "explanation": "CDC debentures are pooled monthly and sold, with funding occurring 4-6 weeks after the pool sale.", "points": 15, "difficulty": "medium"},
  {"question": "Who services the CDC debenture?", "type": "multiple-choice", "options": ["The bank", "The CDC and its Certified Lender Program", "SBA directly", "The borrower"], "correctAnswer": "The CDC and its Certified Lender Program", "explanation": "The CDC services the debenture, monitoring borrower compliance and payments.", "points": 10, "difficulty": "easy"},
  {"question": "What is the prepayment penalty on 504 debentures?", "type": "multiple-choice", "options": ["No penalty", "Declining penalty over first 10 years (50% of remaining term)", "Flat 5%", "3 months interest"], "correctAnswer": "Declining penalty over first 10 years (50% of remaining term)", "explanation": "504 debentures have a declining prepayment penalty based on remaining term for the first half of the loan.", "points": 15, "difficulty": "hard"},
  {"question": "What ongoing reporting does the CDC require?", "type": "multiple-choice", "options": ["Nothing after closing", "Annual financial statements and job reporting", "Monthly financial reports", "Weekly updates"], "correctAnswer": "Annual financial statements and job reporting", "explanation": "CDCs require annual financials and periodic job creation/retention verification.", "points": 10, "difficulty": "easy"}
]'::jsonb),

-- SBA Express Beginner 2-7
('sba-express-module-2-beginner', 'SBA Express Products Quiz', 'quiz', 1, 80, true, 3, 15, '[
  {"question": "What loan structures does SBA Express offer?", "type": "multiple-choice", "options": ["Term loans only", "Term loans and revolving lines of credit", "Only lines of credit", "Only real estate loans"], "correctAnswer": "Term loans and revolving lines of credit", "explanation": "Express offers both term loans and revolving credit facilities.", "points": 10, "difficulty": "easy"},
  {"question": "What is the maximum Express line of credit maturity?", "type": "multiple-choice", "options": ["3 years", "5 years", "7 years", "10 years"], "correctAnswer": "7 years", "explanation": "Express revolving lines have a maximum 7-year maturity.", "points": 15, "difficulty": "medium"},
  {"question": "Can SBA Express be used for real estate?", "type": "multiple-choice", "options": ["No", "Yes, with standard SBA real estate terms", "Only for refinancing", "Only under $250K"], "correctAnswer": "Yes, with standard SBA real estate terms", "explanation": "Express can finance real estate with terms up to 25 years.", "points": 15, "difficulty": "medium"},
  {"question": "What is the advantage of Express over standard 7(a)?", "type": "multiple-choice", "options": ["Higher guarantee", "Faster turnaround using lender own procedures", "Lower interest rates", "No personal guarantee"], "correctAnswer": "Faster turnaround using lender own procedures", "explanation": "Express allows lenders to use their own forms and procedures for faster processing.", "points": 10, "difficulty": "easy"}
]'::jsonb),

('sba-express-module-3-beginner', 'SBA Express Eligibility Quiz', 'quiz', 1, 80, true, 3, 15, '[
  {"question": "Do Express loans have the same eligibility as standard 7(a)?", "type": "multiple-choice", "options": ["No, different requirements", "Yes, same SBA eligibility standards apply", "Express has no requirements", "Only credit score matters"], "correctAnswer": "Yes, same SBA eligibility standards apply", "explanation": "Express follows the same SBA eligibility rules for size, type, and use of proceeds.", "points": 10, "difficulty": "easy"},
  {"question": "Can Express lenders use their own credit scoring?", "type": "multiple-choice", "options": ["No, must use SBA scoring", "Yes, they may use their own underwriting criteria", "Only for loans under $50K", "Only PLP lenders"], "correctAnswer": "Yes, they may use their own underwriting criteria", "explanation": "Express lenders use their own credit analysis and documentation requirements.", "points": 15, "difficulty": "medium"},
  {"question": "Are personal guarantees required for Express loans?", "type": "multiple-choice", "options": ["Never", "Yes, from all owners with 20%+ ownership", "Only over $250K", "Only for startups"], "correctAnswer": "Yes, from all owners with 20%+ ownership", "explanation": "Same as standard 7(a): owners with 20%+ must personally guarantee.", "points": 10, "difficulty": "easy"},
  {"question": "What makes a lender eligible to offer SBA Express?", "type": "multiple-choice", "options": ["Any bank can offer it", "Must be an SBA-approved Express lender", "Only credit unions", "Only community banks"], "correctAnswer": "Must be an SBA-approved Express lender", "explanation": "Lenders must apply and be approved by SBA to participate in the Express program.", "points": 15, "difficulty": "medium"}
]'::jsonb),

('sba-express-module-4-beginner', 'SBA Express Documentation Quiz', 'quiz', 1, 80, true, 3, 15, '[
  {"question": "What documentation can Express lenders use?", "type": "multiple-choice", "options": ["Only SBA forms", "Their own forms supplemented by required SBA forms", "No documentation needed", "Federal Reserve forms"], "correctAnswer": "Their own forms supplemented by required SBA forms", "explanation": "Express lenders may use their own documentation processes plus required SBA-specific forms.", "points": 15, "difficulty": "medium"},
  {"question": "Is SBA Form 1919 required for Express?", "type": "multiple-choice", "options": ["No", "Yes, it is still required for all SBA loans", "Only over $350K", "Only for first-time borrowers"], "correctAnswer": "Yes, it is still required for all SBA loans", "explanation": "The Borrower Information Form is required regardless of the SBA program type.", "points": 10, "difficulty": "easy"},
  {"question": "What collateral documentation is needed for Express under $25K?", "type": "multiple-choice", "options": ["Full collateral package", "No collateral required", "Only personal guarantee", "Real estate appraisal"], "correctAnswer": "No collateral required", "explanation": "SBA does not require collateral for Express loans of $25,000 or less.", "points": 15, "difficulty": "medium"},
  {"question": "How quickly can Express loans close?", "type": "multiple-choice", "options": ["Same day", "Typically 30-45 days from application", "6 months minimum", "1 year"], "correctAnswer": "Typically 30-45 days from application", "explanation": "Streamlined processing allows Express loans to close in 30-45 days.", "points": 10, "difficulty": "easy"}
]'::jsonb),

('sba-express-module-5-beginner', 'SBA Express Financial Analysis Quiz', 'quiz', 1, 80, true, 3, 15, '[
  {"question": "What financial analysis do Express lenders perform?", "type": "multiple-choice", "options": ["No analysis needed", "Their own credit analysis per internal policies", "Only SBA-prescribed analysis", "External auditor review"], "correctAnswer": "Their own credit analysis per internal policies", "explanation": "Express lenders apply their own credit underwriting standards and financial analysis.", "points": 10, "difficulty": "easy"},
  {"question": "What is the typical interest rate spread for Express?", "type": "multiple-choice", "options": ["Prime + 0.5%", "Prime + 2.25-4.5% depending on size/maturity", "Fixed at 5%", "SOFR + 1%"], "correctAnswer": "Prime + 2.25-4.5% depending on size/maturity", "explanation": "Express allows higher spreads than standard 7(a) to compensate for the lower guarantee.", "points": 15, "difficulty": "medium"},
  {"question": "Why are Express rates typically higher than standard 7(a)?", "type": "multiple-choice", "options": ["SBA charges more", "Lower guarantee (50%) means more lender risk", "Express loans are riskier", "Government regulation"], "correctAnswer": "Lower guarantee (50%) means more lender risk", "explanation": "The 50% guarantee (vs 75-85%) means lenders bear more risk, reflected in higher rates.", "points": 15, "difficulty": "medium"},
  {"question": "What is the break-even comparison between Express and conventional?", "type": "multiple-choice", "options": ["Express is always cheaper", "Compare total cost including SBA fees vs conventional rates", "Conventional is always cheaper", "They cost the same"], "correctAnswer": "Compare total cost including SBA fees vs conventional rates", "explanation": "Borrowers should compare all-in costs including guarantee fees, rates, and terms.", "points": 10, "difficulty": "easy"}
]'::jsonb),

('sba-express-module-6-beginner', 'SBA Express Underwriting Quiz', 'quiz', 1, 80, true, 3, 15, '[
  {"question": "Who makes the credit decision on Express loans?", "type": "multiple-choice", "options": ["SBA headquarters", "The lender independently without prior SBA approval", "A committee of lenders", "The CDC"], "correctAnswer": "The lender independently without prior SBA approval", "explanation": "Express lenders have delegated authority to make credit decisions independently.", "points": 10, "difficulty": "easy"},
  {"question": "What is the lender risk in Express vs standard 7(a)?", "type": "multiple-choice", "options": ["Same risk", "Higher - 50% vs 15-25% unguaranteed exposure", "Lower risk", "No risk"], "correctAnswer": "Higher - 50% vs 15-25% unguaranteed exposure", "explanation": "Express lenders retain 50% risk vs 15-25% on standard 7(a) loans.", "points": 15, "difficulty": "medium"},
  {"question": "What underwriting flexibility do Express lenders have?", "type": "multiple-choice", "options": ["None", "Can use their own policies, procedures, and documentation", "Must follow all SBA SOPs exactly", "Only for loans under $100K"], "correctAnswer": "Can use their own policies, procedures, and documentation", "explanation": "Express program grants maximum flexibility in underwriting approach.", "points": 15, "difficulty": "medium"},
  {"question": "What is the lender obligation if Express loans default?", "type": "multiple-choice", "options": ["No obligation", "Must service and liquidate per SBA requirements to claim guarantee", "SBA handles everything", "Borrower handles it"], "correctAnswer": "Must service and liquidate per SBA requirements to claim guarantee", "explanation": "Lenders must follow SBA servicing and liquidation guidelines to receive guarantee payment.", "points": 10, "difficulty": "easy"}
]'::jsonb),

('sba-express-module-7-beginner', 'SBA Express Closing & Management Quiz', 'quiz', 1, 80, true, 3, 15, '[
  {"question": "How does SBA Express guarantee purchase work?", "type": "multiple-choice", "options": ["Automatic at default", "Lender requests purchase after completing liquidation steps", "SBA monitors and acts independently", "Guarantee is immediate"], "correctAnswer": "Lender requests purchase after completing liquidation steps", "explanation": "Lenders must complete required servicing actions before requesting SBA guarantee purchase.", "points": 15, "difficulty": "medium"},
  {"question": "What is the SBA repair requirement before purchase?", "type": "multiple-choice", "options": ["No repairs needed", "Lender must document it followed all SBA requirements", "Physical property repair", "Borrower must fix their credit"], "correctAnswer": "Lender must document it followed all SBA requirements", "explanation": "SBA may deny or reduce the guarantee if the lender did not follow required procedures.", "points": 15, "difficulty": "medium"},
  {"question": "Can Express loans be sold on the secondary market?", "type": "multiple-choice", "options": ["No", "Yes, the guaranteed portion can be sold", "Only loans over $250K", "Only to other SBA lenders"], "correctAnswer": "Yes, the guaranteed portion can be sold", "explanation": "Like standard 7(a), the guaranteed 50% portion can be sold on the secondary market.", "points": 10, "difficulty": "easy"},
  {"question": "What ongoing monitoring is required for Express loans?", "type": "multiple-choice", "options": ["No monitoring", "Lender follows its own monitoring plus SBA reporting", "Daily SBA reports", "Borrower self-reports"], "correctAnswer": "Lender follows its own monitoring plus SBA reporting", "explanation": "Lenders apply their own portfolio monitoring and submit required SBA status reports.", "points": 10, "difficulty": "easy"}
]'::jsonb);
