
-- Case studies for expert-level tracks
INSERT INTO case_studies (module_id, title, company, situation, challenge, solution, outcome, order_index, lessons_learned) VALUES
('sba-7(a)-module-1-expert', 'Complex Multi-Entity Acquisition', 'Heritage Restaurant Group Holdings', 'A private equity-backed group sought to acquire 5 restaurant locations across 3 states simultaneously, requiring $4.2M in SBA 7(a) financing with complex entity structures and inter-company guarantees.', 'The deal involved multiple operating entities, a management company, and a real estate holding company. SBA affiliation rules threatened to disqualify the borrower, and the transaction timeline required coordinated closings across multiple jurisdictions.', 'Structured the transaction with separate SBA 7(a) loans for each operating entity, carefully documenting the absence of affiliation triggers. Negotiated phased closings with escrow arrangements and cross-default provisions that satisfied both the SBA and the sellers.', 'All five acquisitions closed within a 90-day window. Combined revenue exceeded $12M in year one. The group achieved 15% cost savings through centralized purchasing and shared management services, improving DSCR from 1.2x to 1.6x across the portfolio.', 1, '["SBA affiliation rules require careful structuring in multi-entity deals", "Phased closings with escrow arrangements manage complex transaction timing", "Centralized operations create synergies that improve overall debt service", "Cross-jurisdictional deals require coordinated legal counsel in each state"]'::jsonb),

('commercial-real-estate-module-1-expert', 'Distressed Hotel Repositioning', 'Lakeview Hospitality Partners', 'An experienced hotel operator identified a distressed 120-room full-service hotel in a recovering market, available at 40% below replacement cost. The property needed $3.5M in renovations and a complete brand repositioning.', 'The property had been operating at 38% occupancy under poor management. Environmental issues from underground storage tanks required Phase II assessment. The existing franchise agreement was being terminated, requiring a new brand affiliation.', 'Structured a $6.2M acquisition and renovation facility with milestone-based draws for the renovation component. Negotiated a new upscale brand franchise agreement contingent on renovation completion. Environmental remediation was escrowed with state DEQ oversight.', 'After 14-month renovation, the property reopened under the new brand achieving 72% occupancy within 18 months. Revenue per available room (RevPAR) increased 185%. The property appraised at $14M post-renovation, creating substantial equity for the borrower.', 2, '["Distressed hospitality assets can generate exceptional returns with experienced operators", "Environmental issues are manageable when properly assessed and escrowed", "Brand repositioning combined with renovation multiplies value creation", "Milestone-based draw structures protect lender during renovation periods"]'::jsonb),

('construction-loans-module-1-expert', 'Mixed-Use Urban Development', 'Downtown Catalyst Development Corp', 'A developer proposed a 6-story mixed-use project with ground-floor retail, 3 floors of office space, and 2 floors of luxury apartments in a Qualified Opportunity Zone, requiring $18M in total financing.', 'The project involved multiple use types with different risk profiles, tax credit structures (Opportunity Zone, Historic), and required coordination between a construction lender, mezzanine provider, and equity investors. Supply chain disruptions threatened the construction timeline.', 'Structured a $12M senior construction loan with an $3M mezzanine facility and $3M in Opportunity Zone equity. Implemented a guaranteed maximum price contract with the general contractor, material pre-purchasing agreements, and a comprehensive draw management system with dual inspections.', 'Construction completed 3 months behind schedule but within 5% of budget due to contingency reserves and pre-purchased materials. Retail spaces were 80% pre-leased, offices 60% pre-leased, and apartments achieved 95% occupancy within 4 months of certificate of occupancy.', 1, '["Multi-use projects require independent underwriting of each component", "Opportunity Zone structures add complexity but significant tax benefits", "Material pre-purchasing can mitigate supply chain risk effectively", "Dual inspection protocols (lender + owner) reduce draw fraud risk"]'::jsonb),

('equipment-financing-module-1-expert', 'Fleet Electrification Program', 'Metro Delivery Services Inc', 'A last-mile delivery company with 200 diesel vans sought to convert its entire fleet to electric vehicles over 24 months, requiring $8M in equipment financing plus $2M in charging infrastructure.', 'EV technology created residual value uncertainty. Charging infrastructure required utility upgrades with 12-month lead times. The fleet conversion needed to maintain delivery capacity during the transition, requiring a phased approach without service disruption.', 'Designed a master lease facility with quarterly fleet additions, incorporating technology refresh provisions and residual value insurance. Charging infrastructure was financed separately as real property improvements with a 15-year term. State clean energy incentives offset 20% of vehicle costs.', 'Fleet operating costs dropped 42% per mile. The company won two major contracts from ESG-focused retailers specifically because of their electric fleet. Total cost of ownership analysis showed break-even at 4 years vs. diesel, with significant savings beyond.', 2, '["Technology refresh provisions address EV obsolescence risk", "Residual value insurance products exist for emerging technology assets", "Clean energy incentives can materially reduce effective financing costs", "ESG positioning through fleet electrification creates competitive advantages"]'::jsonb),

('asset-based-lending-module-1-expert', 'Turnaround ABL Facility', 'American Textiles Manufacturing Co', 'A 75-year-old textile manufacturer with $45M in revenue faced a liquidity crisis after losing two major retail customers. The company needed a $15M ABL facility to fund restructuring while maintaining operations.', 'The company was in technical default on its existing bank facility. Inventory was partially obsolete, and receivables included disputed amounts. The CEO was replaced, and a turnaround consultant was engaged, but the existing bank was unwilling to continue.', 'Structured a $15M ABL revolving facility with enhanced monitoring: weekly borrowing base certificates, monthly field examinations, inventory sublimits with obsolescence reserves, and a $2M availability block to maintain minimum liquidity. Advance rates were set conservatively at 80% on eligible receivables and 40% on eligible inventory.', 'The company stabilized operations within 6 months, secured 3 new customers, and reduced inventory by 30% through liquidation of obsolete stock. After 18 months, the company was profitable again and refinanced into a less restrictive conventional ABL facility with improved terms.', 1, '["ABL is the financing of last resort for viable businesses in distress", "Enhanced monitoring (weekly BBCs, monthly field exams) is essential for turnaround situations", "Inventory obsolescence reserves protect against inflated collateral values", "Availability blocks ensure minimum liquidity during restructuring periods"]'::jsonb);

-- Additional video content for expert and intermediate tracks
INSERT INTO course_videos (module_id, title, description, video_url, video_type, duration_seconds, order_index, is_active, tags) VALUES
('sba-7(a)-module-1-expert', 'Expert SBA 7(a) Deal Structuring Masterclass', 'Advanced strategies for structuring complex SBA 7(a) transactions including multi-entity deals, partner buyouts, and creative collateral solutions.', 'https://www.youtube.com/watch?v=expert-sba7a-structuring', 'youtube', 2700, 1, true, ARRAY['sba', 'expert', 'deal-structuring']),
('sba-7(a)-module-2-expert', 'Complex Underwriting Case Studies', 'Walk through real-world complex SBA underwriting scenarios with industry-specific adjustments and multi-entity analysis.', 'https://www.youtube.com/watch?v=expert-sba7a-underwriting', 'youtube', 2400, 1, true, ARRAY['sba', 'expert', 'underwriting']),
('commercial-real-estate-module-1-expert', 'CRE Participation & Syndication Structures', 'Deep dive into commercial real estate participation lending, syndication economics, and intercreditor agreements.', 'https://www.youtube.com/watch?v=expert-cre-syndication', 'youtube', 3000, 1, true, ARRAY['cre', 'expert', 'syndication']),
('commercial-real-estate-module-2-expert', 'Advanced CRE Valuation Workshop', 'Hands-on DCF modeling, tenant credit analysis, and environmental risk assessment for commercial properties.', 'https://www.youtube.com/watch?v=expert-cre-valuation', 'youtube', 2700, 1, true, ARRAY['cre', 'expert', 'valuation']),
('construction-loans-module-1-expert', 'Expert Construction Draw Management', 'Advanced draw management systems, cost overrun mitigation, and multi-phase development oversight strategies.', 'https://www.youtube.com/watch?v=expert-construction-draws', 'youtube', 2400, 1, true, ARRAY['construction', 'expert', 'draw-management']),
('equipment-financing-module-1-expert', 'Strategic Equipment Finance Solutions', 'Tax-optimized structures, technology obsolescence management, and sale-leaseback transaction analysis.', 'https://www.youtube.com/watch?v=expert-equipment-strategies', 'youtube', 2100, 1, true, ARRAY['equipment', 'expert', 'tax-optimization']),
('sba-504-module-1-expert', 'SBA 504 Advanced Strategies Workshop', 'Debenture market dynamics, manufacturing provisions, and sophisticated refinancing strategies for the 504 program.', 'https://www.youtube.com/watch?v=expert-sba504-advanced', 'youtube', 2400, 1, true, ARRAY['sba-504', 'expert', 'debenture']),
('working-capital-module-1-expert', 'Working Capital Optimization Masterclass', 'Cash conversion cycle analysis, dynamic borrowing base design, and treasury management integration.', 'https://www.youtube.com/watch?v=expert-working-capital', 'youtube', 2700, 1, true, ARRAY['working-capital', 'expert', 'treasury']),
('invoice-factoring-module-1-expert', 'Advanced Factoring Portfolio Management', 'Account debtor risk stratification, cross-border factoring, and technology-driven factoring operations.', 'https://www.youtube.com/watch?v=expert-factoring-portfolio', 'youtube', 2100, 1, true, ARRAY['factoring', 'expert', 'portfolio']),
('franchise-financing-module-1-expert', 'Multi-Unit Franchise Finance Strategies', 'Area development financing, franchisor analysis, and franchise resale transaction structuring.', 'https://www.youtube.com/watch?v=expert-franchise-multiunit', 'youtube', 2400, 1, true, ARRAY['franchise', 'expert', 'multi-unit']),
('healthcare-financing-module-1-expert', 'Healthcare Practice Valuation & Finance', 'Reimbursement risk assessment, practice valuation methodologies, and regulatory compliance lending.', 'https://www.youtube.com/watch?v=expert-healthcare-valuation', 'youtube', 2700, 1, true, ARRAY['healthcare', 'expert', 'valuation']),
('asset-based-lending-module-1-expert', 'ABL Turnaround Lending Workshop', 'Multi-tranche facility design, DIP financing structures, and field examination best practices.', 'https://www.youtube.com/watch?v=expert-abl-turnaround', 'youtube', 3000, 1, true, ARRAY['abl', 'expert', 'turnaround']);
