
-- Batch 1: Insert assessments for all beginner Module 1s across all course types
INSERT INTO course_assessments (module_id, title, assessment_type, order_index, passing_score, is_required, max_attempts, time_limit_minutes, questions) VALUES

-- SBA 7(a) Beginner (7 modules)
('sba-7(a)-module-1-beginner', 'SBA 7(a) Program Fundamentals Quiz', 'quiz', 1, 80, true, 3, 15, '[
  {"question": "What is the maximum loan amount for an SBA 7(a) loan?", "type": "multiple-choice", "options": ["$1 million", "$2 million", "$5 million", "$10 million"], "correctAnswer": "$5 million", "explanation": "The SBA 7(a) program allows loans up to $5 million for eligible small businesses.", "points": 10, "difficulty": "easy"},
  {"question": "Which federal agency guarantees SBA 7(a) loans?", "type": "multiple-choice", "options": ["Federal Reserve", "FDIC", "Small Business Administration", "Treasury Department"], "correctAnswer": "Small Business Administration", "explanation": "The U.S. Small Business Administration provides the government guarantee on 7(a) loans.", "points": 10, "difficulty": "easy"},
  {"question": "What is the typical SBA guarantee percentage for loans up to $150,000?", "type": "multiple-choice", "options": ["50%", "65%", "75%", "85%"], "correctAnswer": "85%", "explanation": "SBA guarantees up to 85% for loans of $150,000 or less, and 75% for loans above $150,000.", "points": 15, "difficulty": "medium"},
  {"question": "Which business is NOT eligible for SBA 7(a) financing?", "type": "multiple-choice", "options": ["Restaurant franchise", "Real estate investment company", "Manufacturing firm", "Retail store"], "correctAnswer": "Real estate investment company", "explanation": "Passive real estate investment companies are ineligible. The business must be actively operated.", "points": 15, "difficulty": "medium"}
]'::jsonb),

('sba-7(a)-module-2-beginner', 'SBA 7(a) Product Structures Quiz', 'quiz', 1, 80, true, 3, 15, '[
  {"question": "What is the maximum term for SBA 7(a) working capital loans?", "type": "multiple-choice", "options": ["5 years", "7 years", "10 years", "25 years"], "correctAnswer": "10 years", "explanation": "Working capital loans have a maximum 10-year term under 7(a).", "points": 10, "difficulty": "easy"},
  {"question": "What is the maximum term for real estate under 7(a)?", "type": "multiple-choice", "options": ["10 years", "15 years", "20 years", "25 years"], "correctAnswer": "25 years", "explanation": "Real estate purchases can be financed up to 25 years.", "points": 10, "difficulty": "easy"},
  {"question": "Which SBA 7(a) type offers a revolving line of credit?", "type": "multiple-choice", "options": ["Standard 7(a)", "SBA Express", "CAPLines", "Export Express"], "correctAnswer": "CAPLines", "explanation": "CAPLines is specifically designed for revolving lines of credit.", "points": 15, "difficulty": "medium"},
  {"question": "What interest rate structure do most 7(a) loans use?", "type": "multiple-choice", "options": ["Fixed only", "Variable only", "Prime + spread (variable)", "SOFR-based only"], "correctAnswer": "Prime + spread (variable)", "explanation": "Most use a variable rate tied to the Prime rate plus a spread.", "points": 15, "difficulty": "medium"}
]'::jsonb),

('sba-7(a)-module-3-beginner', 'SBA 7(a) Borrower Eligibility Quiz', 'quiz', 1, 80, true, 3, 15, '[
  {"question": "What is the SBA size standard test based on?", "type": "multiple-choice", "options": ["Revenue only", "Employee count only", "Revenue or employee count by NAICS code", "Total assets"], "correctAnswer": "Revenue or employee count by NAICS code", "explanation": "SBA defines eligibility using revenue or employee thresholds by NAICS code.", "points": 10, "difficulty": "easy"},
  {"question": "What minimum credit score is typically needed?", "type": "multiple-choice", "options": ["580", "620", "680", "720"], "correctAnswer": "680", "explanation": "Most SBA lenders require a minimum FICO of 680.", "points": 10, "difficulty": "easy"},
  {"question": "What does the credit elsewhere test evaluate?", "type": "multiple-choice", "options": ["Whether borrower has other SBA loans", "Whether borrower can get credit without SBA help", "Whether competitors declined the loan", "Whether borrower has bank relationships"], "correctAnswer": "Whether borrower can get credit without SBA help", "explanation": "It determines if the borrower needs the SBA guarantee because they cannot get reasonable conventional terms.", "points": 15, "difficulty": "medium"},
  {"question": "Personal guarantees are required from owners with what minimum stake?", "type": "multiple-choice", "options": ["10%", "15%", "20%", "25%"], "correctAnswer": "20%", "explanation": "All owners with 20%+ ownership must provide unlimited personal guarantees.", "points": 15, "difficulty": "medium"}
]'::jsonb),

('sba-7(a)-module-4-beginner', 'SBA 7(a) Documentation Quiz', 'quiz', 1, 80, true, 3, 15, '[
  {"question": "What is the primary SBA application form?", "type": "multiple-choice", "options": ["SBA Form 1919", "SBA Form 1920", "SBA Form 413", "SBA Form 912"], "correctAnswer": "SBA Form 1919", "explanation": "SBA Form 1919 (Borrower Information Form) is the primary application.", "points": 10, "difficulty": "easy"},
  {"question": "How many years of tax returns are typically required?", "type": "multiple-choice", "options": ["1 year", "2 years", "3 years", "5 years"], "correctAnswer": "3 years", "explanation": "SBA typically requires 3 years of business and personal tax returns.", "points": 10, "difficulty": "easy"},
  {"question": "What form is used for personal financial statements?", "type": "multiple-choice", "options": ["SBA Form 413", "SBA Form 912", "SBA Form 1050", "SBA Form 159"], "correctAnswer": "SBA Form 413", "explanation": "SBA Form 413 is required from all owners with 20%+ ownership.", "points": 15, "difficulty": "medium"},
  {"question": "What does SBA Form 912 evaluate?", "type": "multiple-choice", "options": ["Financial projections", "Character and criminal background", "Environmental compliance", "Franchise agreements"], "correctAnswer": "Character and criminal background", "explanation": "Form 912 screens for criminal background and character eligibility.", "points": 15, "difficulty": "hard"}
]'::jsonb),

('sba-7(a)-module-5-beginner', 'SBA 7(a) Financial Analysis Quiz', 'quiz', 1, 80, true, 3, 15, '[
  {"question": "What minimum DSCR is typically required for SBA 7(a)?", "type": "multiple-choice", "options": ["0.8x", "1.0x", "1.15x", "1.5x"], "correctAnswer": "1.15x", "explanation": "Most lenders require 1.15x DSCR minimum.", "points": 10, "difficulty": "medium"},
  {"question": "How is DSCR calculated?", "type": "multiple-choice", "options": ["Net income / Total debt", "EBITDA / Annual debt service", "Gross revenue / Loan amount", "Net worth / Total liabilities"], "correctAnswer": "EBITDA / Annual debt service", "explanation": "DSCR = EBITDA divided by total annual debt service.", "points": 15, "difficulty": "medium"},
  {"question": "What ratio measures short-term obligation ability?", "type": "multiple-choice", "options": ["Debt-to-equity", "Current ratio", "Return on assets", "Gross margin"], "correctAnswer": "Current ratio", "explanation": "Current ratio (current assets / current liabilities) measures short-term liquidity.", "points": 10, "difficulty": "easy"},
  {"question": "Why are financial projections important in SBA lending?", "type": "multiple-choice", "options": ["Legally required by SBA", "Demonstrate future repayment ability", "Replace the need for tax returns", "Determine the interest rate"], "correctAnswer": "Demonstrate future repayment ability", "explanation": "Projections show the lender the business will generate sufficient cash flow.", "points": 10, "difficulty": "easy"}
]'::jsonb),

('sba-7(a)-module-6-beginner', 'SBA 7(a) Underwriting Quiz', 'quiz', 1, 80, true, 3, 15, '[
  {"question": "What are the 5 Cs of credit?", "type": "multiple-choice", "options": ["Cost, Capital, Coverage, Compliance, Collateral", "Character, Capacity, Capital, Collateral, Conditions", "Credit, Cash flow, Capitalization, Compliance, Character", "Capacity, Coverage, Collateral, Conditions, Compliance"], "correctAnswer": "Character, Capacity, Capital, Collateral, Conditions", "explanation": "The 5 Cs evaluate Character, Capacity, Capital, Collateral, and Conditions.", "points": 10, "difficulty": "easy"},
  {"question": "What is the SBA collateral shortfall policy?", "type": "multiple-choice", "options": ["Cannot decline for insufficient collateral alone", "100% coverage always required", "At least 50% coverage needed", "Only real estate accepted"], "correctAnswer": "Cannot decline for insufficient collateral alone", "explanation": "SBA policy states loans should not be declined solely due to inadequate collateral.", "points": 15, "difficulty": "hard"},
  {"question": "What is the primary repayment source for SBA 7(a)?", "type": "multiple-choice", "options": ["Collateral liquidation", "Personal assets", "Business cash flow", "SBA guarantee funds"], "correctAnswer": "Business cash flow", "explanation": "Primary repayment is always business cash flow from operations.", "points": 10, "difficulty": "easy"},
  {"question": "When is an environmental review required?", "type": "multiple-choice", "options": ["All SBA loans", "Loans with real estate collateral", "Manufacturing only", "Only loans over $1M"], "correctAnswer": "Loans with real estate collateral", "explanation": "Environmental reviews are required when real estate is used as collateral.", "points": 15, "difficulty": "medium"}
]'::jsonb),

('sba-7(a)-module-7-beginner', 'SBA 7(a) Closing & Servicing Quiz', 'quiz', 1, 80, true, 3, 15, '[
  {"question": "What is the SBA guaranty fee based on?", "type": "multiple-choice", "options": ["Total loan amount", "Guaranteed portion", "Interest rate", "Loan term"], "correctAnswer": "Guaranteed portion", "explanation": "The fee is calculated on the guaranteed portion, not total loan amount.", "points": 10, "difficulty": "easy"},
  {"question": "What document secures the SBA lien on assets?", "type": "multiple-choice", "options": ["Promissory note", "UCC-1 filing", "Personal guarantee", "Business plan"], "correctAnswer": "UCC-1 filing", "explanation": "A UCC-1 filing perfects the lender interest in business assets.", "points": 10, "difficulty": "easy"},
  {"question": "How often must lenders report to SBA?", "type": "multiple-choice", "options": ["Weekly", "Monthly", "Quarterly", "Annually"], "correctAnswer": "Monthly", "explanation": "Lenders submit monthly status reports to the SBA.", "points": 15, "difficulty": "medium"},
  {"question": "What triggers an SBA loan default?", "type": "multiple-choice", "options": ["Missing one payment", "60+ days delinquent or covenant violations", "Revenue decline of 10%", "Change in location"], "correctAnswer": "60+ days delinquent or covenant violations", "explanation": "Default is triggered by 60+ days past due or violating loan covenants.", "points": 15, "difficulty": "medium"}
]'::jsonb),

-- SBA 504 Beginner (7 modules)
('sba-504-module-1-beginner', 'SBA 504 Program Fundamentals Quiz', 'quiz', 1, 80, true, 3, 15, '[
  {"question": "What is the primary purpose of the SBA 504 program?", "type": "multiple-choice", "options": ["Working capital", "Fixed asset acquisition", "Inventory purchasing", "Debt refinancing only"], "correctAnswer": "Fixed asset acquisition", "explanation": "The 504 program is for major fixed asset purchases like real estate and heavy equipment.", "points": 10, "difficulty": "easy"},
  {"question": "What is the typical 504 financing structure?", "type": "multiple-choice", "options": ["100% SBA funded", "50% bank / 40% CDC / 10% borrower", "75% bank / 25% borrower", "60% SBA / 40% borrower"], "correctAnswer": "50% bank / 40% CDC / 10% borrower", "explanation": "Standard 504: 50% bank, 40% CDC-backed debenture, 10% borrower equity.", "points": 15, "difficulty": "medium"},
  {"question": "What does CDC stand for?", "type": "multiple-choice", "options": ["Commercial Development Corp", "Certified Development Company", "Community Development Center", "Credit Development Company"], "correctAnswer": "Certified Development Company", "explanation": "CDCs are SBA-certified nonprofits that work with lenders to provide 504 financing.", "points": 10, "difficulty": "easy"},
  {"question": "What is the maximum CDC debenture?", "type": "multiple-choice", "options": ["$2 million", "$5 million", "$5.5 million", "$10 million"], "correctAnswer": "$5.5 million", "explanation": "Maximum CDC debenture is $5.5 million for standard projects.", "points": 15, "difficulty": "medium"}
]'::jsonb),

-- SBA Express Beginner (7 modules)
('sba-express-module-1-beginner', 'SBA Express Fundamentals Quiz', 'quiz', 1, 80, true, 3, 15, '[
  {"question": "What is the maximum SBA Express loan amount?", "type": "multiple-choice", "options": ["$150,000", "$350,000", "$500,000", "$1 million"], "correctAnswer": "$500,000", "explanation": "SBA Express has a $500,000 maximum with expedited approval.", "points": 10, "difficulty": "easy"},
  {"question": "What is the SBA Express guarantee percentage?", "type": "multiple-choice", "options": ["50%", "65%", "75%", "85%"], "correctAnswer": "50%", "explanation": "Express provides 50% guarantee, lower than standard 7(a) but faster.", "points": 10, "difficulty": "easy"},
  {"question": "What is the target SBA response time for Express?", "type": "multiple-choice", "options": ["24 hours", "36 hours", "72 hours", "5 business days"], "correctAnswer": "36 hours", "explanation": "SBA targets 36-hour turnaround for Express authorization.", "points": 15, "difficulty": "medium"},
  {"question": "Can Express loans be revolving lines of credit?", "type": "multiple-choice", "options": ["No, term only", "Yes, up to 7 years", "Yes, up to 10 years", "Only with special approval"], "correctAnswer": "Yes, up to 7 years", "explanation": "SBA Express allows revolving lines up to 7 years.", "points": 15, "difficulty": "medium"}
]'::jsonb),

-- CRE Beginner Module 1
('commercial-real-estate-module-1-beginner', 'CRE Lending Fundamentals Quiz', 'quiz', 1, 80, true, 3, 15, '[
  {"question": "What property types are classified as CRE?", "type": "multiple-choice", "options": ["Single-family homes only", "Office, retail, industrial, multifamily (5+ units)", "Only properties over $1M", "Any business property"], "correctAnswer": "Office, retail, industrial, multifamily (5+ units)", "explanation": "CRE includes office, retail, industrial, multifamily (5+), hospitality, and special-purpose.", "points": 10, "difficulty": "easy"},
  {"question": "What is the typical CRE LTV ratio?", "type": "multiple-choice", "options": ["50-60%", "65-75%", "75-80%", "90-95%"], "correctAnswer": "75-80%", "explanation": "Most CRE loans offer 75-80% LTV, requiring 20-25% equity.", "points": 10, "difficulty": "easy"},
  {"question": "What is Net Operating Income (NOI)?", "type": "multiple-choice", "options": ["Gross revenue minus all expenses", "Revenue minus operating expenses (excluding debt service)", "Net profit after taxes", "Cash flow after debt"], "correctAnswer": "Revenue minus operating expenses (excluding debt service)", "explanation": "NOI = Gross income minus vacancy and operating expenses, before debt service.", "points": 15, "difficulty": "medium"},
  {"question": "What is the cap rate formula?", "type": "multiple-choice", "options": ["NOI × Property Value", "NOI / Purchase Price", "Debt Service / NOI", "Cash Flow / Equity"], "correctAnswer": "NOI / Purchase Price", "explanation": "Cap Rate = NOI / Property Value, used to estimate CRE returns.", "points": 15, "difficulty": "medium"}
]'::jsonb),

-- Construction Beginner Module 1
('construction-loans-module-1-beginner', 'Construction Lending Fundamentals Quiz', 'quiz', 1, 80, true, 3, 15, '[
  {"question": "How are construction loan funds disbursed?", "type": "multiple-choice", "options": ["Lump sum at closing", "Monthly installments", "Progress-based draws after inspections", "Quarterly"], "correctAnswer": "Progress-based draws after inspections", "explanation": "Funds are disbursed through draws tied to milestones verified by inspections.", "points": 10, "difficulty": "easy"},
  {"question": "What is an interest reserve?", "type": "multiple-choice", "options": ["Extra collateral", "Funds set aside to pay interest during construction", "Early completion penalty", "Cost overrun insurance"], "correctAnswer": "Funds set aside to pay interest during construction", "explanation": "Interest reserves fund payments during construction when no income is generated.", "points": 15, "difficulty": "medium"},
  {"question": "What is a take-out commitment?", "type": "multiple-choice", "options": ["Demolition agreement", "Permanent financing upon completion", "Defect insurance", "Performance bond"], "correctAnswer": "Permanent financing upon completion", "explanation": "A take-out is a permanent lender commitment to refinance the construction loan.", "points": 15, "difficulty": "medium"},
  {"question": "What is the typical LTC ratio?", "type": "multiple-choice", "options": ["50-60%", "65-75%", "80-90%", "95-100%"], "correctAnswer": "65-75%", "explanation": "Construction loans fund 65-75% of total project costs.", "points": 10, "difficulty": "easy"}
]'::jsonb),

-- Equipment Beginner Module 1
('equipment-financing-module-1-beginner', 'Equipment Financing Fundamentals Quiz', 'quiz', 1, 80, true, 3, 15, '[
  {"question": "What is the typical equipment financing LTV?", "type": "multiple-choice", "options": ["60-70%", "70-80%", "80-90%", "95-100%"], "correctAnswer": "80-90%", "explanation": "Equipment financing offers 80-90% LTV since the equipment is primary collateral.", "points": 10, "difficulty": "easy"},
  {"question": "What document secures lender interest in equipment?", "type": "multiple-choice", "options": ["Bill of sale", "UCC-1 filing", "Equipment warranty", "Purchase agreement"], "correctAnswer": "UCC-1 filing", "explanation": "UCC-1 perfects the lender security interest in equipment collateral.", "points": 10, "difficulty": "easy"},
  {"question": "How does useful life affect loan structuring?", "type": "multiple-choice", "options": ["No impact", "Term should not exceed useful life", "Longer life means higher rates", "Only matters for leases"], "correctAnswer": "Term should not exceed useful life", "explanation": "Loan maturity should match or be shorter than equipment useful life.", "points": 15, "difficulty": "medium"},
  {"question": "Difference between equipment loan and lease?", "type": "multiple-choice", "options": ["No difference", "Loans transfer ownership; leases may not", "Leases always cost more", "Loans only for new equipment"], "correctAnswer": "Loans transfer ownership; leases may not", "explanation": "Loans give ownership; leases may be operating (no transfer) or capital (transfer).", "points": 15, "difficulty": "medium"}
]'::jsonb),

-- Working Capital Beginner Module 1
('working-capital-module-1-beginner', 'Working Capital Fundamentals Quiz', 'quiz', 1, 80, true, 3, 15, '[
  {"question": "How is working capital calculated?", "type": "multiple-choice", "options": ["Revenue minus expenses", "Current assets minus current liabilities", "Total assets minus total debt", "Cash minus accounts payable"], "correctAnswer": "Current assets minus current liabilities", "explanation": "Working capital = current assets - current liabilities.", "points": 10, "difficulty": "easy"},
  {"question": "Primary use of a working capital loan?", "type": "multiple-choice", "options": ["Purchasing real estate", "Funding day-to-day operations", "Long-term equipment", "Acquisitions"], "correctAnswer": "Funding day-to-day operations", "explanation": "Working capital loans fund everyday needs: payroll, inventory, rent.", "points": 10, "difficulty": "easy"},
  {"question": "What does cash conversion cycle measure?", "type": "multiple-choice", "options": ["Revenue growth", "Time to convert inventory/receivables to cash", "Profit margin", "Debt repayment timeline"], "correctAnswer": "Time to convert inventory/receivables to cash", "explanation": "It measures how long to convert inventory purchases into cash from sales.", "points": 15, "difficulty": "medium"},
  {"question": "Which business most likely needs working capital?", "type": "multiple-choice", "options": ["No seasonal variation", "Seasonal retailer preparing for holidays", "Real estate investor", "Startup with no revenue"], "correctAnswer": "Seasonal retailer preparing for holidays", "explanation": "Seasonal businesses need working capital to build inventory before peak seasons.", "points": 15, "difficulty": "medium"}
]'::jsonb),

-- Invoice Factoring Beginner Module 1
('invoice-factoring-module-1-beginner', 'Invoice Factoring Fundamentals Quiz', 'quiz', 1, 80, true, 3, 15, '[
  {"question": "What is invoice factoring?", "type": "multiple-choice", "options": ["Equipment loan", "Selling receivables at a discount for cash", "Revenue-based credit line", "Bad debt insurance"], "correctAnswer": "Selling receivables at a discount for cash", "explanation": "Factoring = selling outstanding invoices to a factor for immediate cash.", "points": 10, "difficulty": "easy"},
  {"question": "Typical advance rate in factoring?", "type": "multiple-choice", "options": ["50-60%", "70-80%", "80-90%", "95-100%"], "correctAnswer": "80-90%", "explanation": "Factors advance 80-90% of face value; remainder paid when collected.", "points": 10, "difficulty": "easy"},
  {"question": "Recourse vs non-recourse factoring?", "type": "multiple-choice", "options": ["Recourse is cheaper", "In recourse, business buys back uncollectibles", "They are identical", "Non-recourse means factor collects directly"], "correctAnswer": "In recourse, business buys back uncollectibles", "explanation": "Recourse: business bears credit risk. Non-recourse: factor takes the risk.", "points": 15, "difficulty": "medium"},
  {"question": "What is the factoring reserve?", "type": "multiple-choice", "options": ["Money held by business", "Portion withheld until invoice collected", "Insurance deposit", "Processing fee"], "correctAnswer": "Portion withheld until invoice collected", "explanation": "Reserve (10-20%) is held by factor, released minus fees when customer pays.", "points": 15, "difficulty": "medium"}
]'::jsonb),

-- MCA Beginner Module 1
('merchant-cash-advances-module-1-beginner', 'MCA Fundamentals Quiz', 'quiz', 1, 80, true, 3, 15, '[
  {"question": "How is an MCA repaid?", "type": "multiple-choice", "options": ["Fixed monthly payments", "Percentage of daily card sales", "Balloon at maturity", "Annual lump sum"], "correctAnswer": "Percentage of daily card sales", "explanation": "MCAs are repaid via a holdback percentage of daily card sales.", "points": 10, "difficulty": "easy"},
  {"question": "What is a factor rate in MCA?", "type": "multiple-choice", "options": ["Interest rate", "Multiplier for total repayment", "Daily holdback %", "Credit threshold"], "correctAnswer": "Multiplier for total repayment", "explanation": "Factor rates (1.2-1.5) multiply the advance to determine total repayment.", "points": 15, "difficulty": "medium"},
  {"question": "Why is MCA not technically a loan?", "type": "multiple-choice", "options": ["Different application", "Purchase of future receivables", "No credit check", "No written agreement"], "correctAnswer": "Purchase of future receivables", "explanation": "MCAs are structured as a purchase of future sales, not a loan.", "points": 15, "difficulty": "medium"},
  {"question": "Typical holdback percentage?", "type": "multiple-choice", "options": ["1-5%", "10-20%", "25-35%", "40-50%"], "correctAnswer": "10-20%", "explanation": "Most MCAs withhold 10-20% of daily card sales.", "points": 10, "difficulty": "easy"}
]'::jsonb),

-- Franchise Beginner Module 1
('franchise-financing-module-1-beginner', 'Franchise Financing Fundamentals Quiz', 'quiz', 1, 80, true, 3, 15, '[
  {"question": "What document must be reviewed before financing a franchise?", "type": "multiple-choice", "options": ["Business plan only", "Franchise Disclosure Document (FDD)", "Marketing materials", "Annual report"], "correctAnswer": "Franchise Disclosure Document (FDD)", "explanation": "The FDD contains 23 required disclosure items.", "points": 10, "difficulty": "easy"},
  {"question": "What is a franchise fee?", "type": "multiple-choice", "options": ["Monthly rent", "Upfront payment for brand rights", "Equipment lease", "Marketing contribution"], "correctAnswer": "Upfront payment for brand rights", "explanation": "The franchise fee grants the right to operate under the franchisor brand.", "points": 10, "difficulty": "easy"},
  {"question": "Why is FDD Item 19 important for lenders?", "type": "multiple-choice", "options": ["Lists equipment", "Financial performance representations", "Describes territory", "Litigation history"], "correctAnswer": "Financial performance representations", "explanation": "Item 19 has earnings claims and financial data for cash flow assessment.", "points": 15, "difficulty": "medium"},
  {"question": "Typical SBA eligibility requirement for franchise lending?", "type": "multiple-choice", "options": ["Must be under 5 years old", "Must be on SBA Franchise Directory", "Must have restaurant experience", "Fee must be under $50K"], "correctAnswer": "Must be on SBA Franchise Directory", "explanation": "The franchise must be on the SBA Franchise Directory.", "points": 15, "difficulty": "medium"}
]'::jsonb),

-- Healthcare Beginner Module 1
('healthcare-financing-module-1-beginner', 'Healthcare Financing Fundamentals Quiz', 'quiz', 1, 80, true, 3, 15, '[
  {"question": "What makes healthcare lending unique?", "type": "multiple-choice", "options": ["Lower rates", "Revenue depends on insurance reimbursements and regulation", "No collateral needed", "Shorter terms"], "correctAnswer": "Revenue depends on insurance reimbursements and regulation", "explanation": "Healthcare revenue is tied to payer mix and extensive regulations.", "points": 15, "difficulty": "medium"},
  {"question": "What is AR concentration risk in healthcare?", "type": "multiple-choice", "options": ["Too many patients", "Over-reliance on a single payer source", "High turnover", "Equipment depreciation"], "correctAnswer": "Over-reliance on a single payer source", "explanation": "High dependence on one payer creates risk if their policies change.", "points": 15, "difficulty": "medium"},
  {"question": "What is a Certificate of Need (CON)?", "type": "multiple-choice", "options": ["Medical license", "State approval to build/expand healthcare facilities", "Insurance certification", "Patient consent"], "correctAnswer": "State approval to build/expand healthcare facilities", "explanation": "CON laws require government approval before expanding healthcare facilities.", "points": 10, "difficulty": "easy"},
  {"question": "Which healthcare sector typically has highest margins?", "type": "multiple-choice", "options": ["Rural hospitals", "Specialty medical practices", "Long-term care", "Community health centers"], "correctAnswer": "Specialty medical practices", "explanation": "Specialties like dermatology achieve higher margins from favorable reimbursement.", "points": 10, "difficulty": "easy"}
]'::jsonb),

-- Restaurant Beginner Module 1
('restaurant-financing-module-1-beginner', 'Restaurant Financing Fundamentals Quiz', 'quiz', 1, 80, true, 3, 15, '[
  {"question": "Typical failure rate for new restaurants in year one?", "type": "multiple-choice", "options": ["10%", "30%", "60%", "80%"], "correctAnswer": "60%", "explanation": "~60% of restaurants fail within the first year.", "points": 10, "difficulty": "easy"},
  {"question": "Ideal food cost percentage?", "type": "multiple-choice", "options": ["15-20%", "25-35%", "40-50%", "55-65%"], "correctAnswer": "25-35%", "explanation": "Industry standard food cost is 25-35% of revenue.", "points": 15, "difficulty": "medium"},
  {"question": "What is prime cost in restaurant finance?", "type": "multiple-choice", "options": ["Building cost", "Food cost + labor cost", "Equipment depreciation", "Franchise fees"], "correctAnswer": "Food cost + labor cost", "explanation": "Prime cost = food + labor, targeted at 55-65% of revenue.", "points": 15, "difficulty": "medium"},
  {"question": "Why do lenders require personal guarantees for restaurants?", "type": "multiple-choice", "options": ["Legally required", "Restaurant assets have limited liquidation value", "High revenue", "Reduces interest rates"], "correctAnswer": "Restaurant assets have limited liquidation value", "explanation": "Restaurant equipment and improvements have low resale value.", "points": 10, "difficulty": "easy"}
]'::jsonb),

-- Asset-Based Lending Beginner Module 1
('asset-based-lending-module-1-beginner', 'ABL Fundamentals Quiz', 'quiz', 1, 80, true, 3, 15, '[
  {"question": "What is asset-based lending?", "type": "multiple-choice", "options": ["Credit score lending", "Lending secured by business assets with advance rates", "Unsecured loans", "Government-guaranteed lending"], "correctAnswer": "Lending secured by business assets with advance rates", "explanation": "ABL is secured by specific collateral with borrowing tied to asset values.", "points": 10, "difficulty": "easy"},
  {"question": "What is a borrowing base?", "type": "multiple-choice", "options": ["Minimum loan amount", "Max borrowing capacity from eligible collateral", "Interest rate floor", "Total company asset value"], "correctAnswer": "Max borrowing capacity from eligible collateral", "explanation": "Borrowing base applies advance rates to eligible collateral for available credit.", "points": 15, "difficulty": "medium"},
  {"question": "Typical advance rate on eligible receivables?", "type": "multiple-choice", "options": ["50-60%", "70-75%", "80-85%", "95-100%"], "correctAnswer": "80-85%", "explanation": "Eligible receivables get 80-85% advance rate.", "points": 10, "difficulty": "easy"},
  {"question": "What makes a receivable ineligible in ABL?", "type": "multiple-choice", "options": ["From Fortune 500", "Over 90 days past due or cross-aged", "In US dollars", "From recurring customer"], "correctAnswer": "Over 90 days past due or cross-aged", "explanation": "Receivables over 90 days, cross-aged, intercompany, or foreign are typically ineligible.", "points": 15, "difficulty": "medium"}
]'::jsonb),

-- Business Lines of Credit Beginner Module 1
('business-lines-of-credit-module-1-beginner', 'Business Lines of Credit Fundamentals Quiz', 'quiz', 1, 80, true, 3, 15, '[
  {"question": "What is a business line of credit?", "type": "multiple-choice", "options": ["One-time lump sum loan", "Revolving credit facility with a set limit", "Equipment lease", "Factoring arrangement"], "correctAnswer": "Revolving credit facility with a set limit", "explanation": "A line of credit provides flexible, revolving access to funds up to an approved limit.", "points": 10, "difficulty": "easy"},
  {"question": "How does interest accrue on a line of credit?", "type": "multiple-choice", "options": ["On the full credit limit", "Only on the outstanding drawn balance", "Flat monthly fee", "Annual lump sum"], "correctAnswer": "Only on the outstanding drawn balance", "explanation": "Interest is charged only on funds actually drawn, not the entire credit limit.", "points": 10, "difficulty": "easy"},
  {"question": "What is a commitment fee on unused credit?", "type": "multiple-choice", "options": ["Penalty for early repayment", "Fee charged on the undrawn portion of the line", "Application processing fee", "Annual renewal charge"], "correctAnswer": "Fee charged on the undrawn portion of the line", "explanation": "Lenders may charge 0.25-0.50% on unused portions to compensate for committed capital.", "points": 15, "difficulty": "medium"},
  {"question": "What triggers a line of credit annual review?", "type": "multiple-choice", "options": ["Nothing, it auto-renews", "Lender reviews financials and may adjust terms", "Only if payments are missed", "Only upon borrower request"], "correctAnswer": "Lender reviews financials and may adjust terms", "explanation": "Annual reviews assess ongoing creditworthiness and may result in limit adjustments.", "points": 15, "difficulty": "medium"}
]'::jsonb);
