
-- Expert-level articles for SBA 7(a) track
INSERT INTO course_articles (module_id, title, content, order_index, is_published, reading_time_minutes, category, excerpt) VALUES
('sba-7(a)-module-1-expert', 'Advanced SBA 7(a) Program Mastery', '<h2>Strategic SBA 7(a) Lending at the Expert Level</h2><p>At the expert level, SBA 7(a) lending transcends basic program knowledge and enters the realm of strategic portfolio management, complex deal structuring, and regulatory navigation. This article explores the advanced competencies required to become a top-performing SBA lender.</p><h3>Complex Deal Structuring</h3><p>Expert SBA lenders understand how to structure multi-layered transactions that optimize borrower outcomes while maintaining compliance. This includes partner buyouts with seller notes, multi-location acquisitions with phased disbursements, and working capital facilities paired with equipment term loans.</p><h3>Portfolio Risk Management</h3><p>Managing an SBA portfolio requires sophisticated risk assessment beyond individual loan analysis. Experts monitor concentration risk by industry, geography, and loan type while maintaining repair rates that satisfy both the SBA and their institution.</p><h3>Regulatory Navigation</h3><p>The SBA Standard Operating Procedures (SOPs) span thousands of pages. Expert lenders develop deep familiarity with nuanced provisions including change of ownership rules, assumption protocols, and liquidation procedures that separate competent lenders from true specialists.</p>', 1, true, 12, 'Expert Analysis', 'Master advanced SBA 7(a) deal structuring, portfolio risk management, and regulatory navigation strategies.'),

('sba-7(a)-module-2-expert', 'Complex SBA 7(a) Underwriting Strategies', '<h2>Advanced Underwriting for Complex Transactions</h2><p>Expert-level SBA 7(a) underwriting goes beyond standard credit analysis to address multi-entity structures, unusual cash flow patterns, and creative collateral arrangements.</p><h3>Multi-Entity Analysis</h3><p>Many SBA borrowers operate through multiple entities. Expert underwriters must consolidate financial statements, identify intercompany transactions, and assess the true economic picture of affiliated businesses while ensuring compliance with affiliation rules.</p><h3>Industry-Specific Adjustments</h3><p>Different industries require specialized underwriting approaches. Healthcare practices need adjustments for provider compensation, hospitality businesses require seasonal cash flow analysis, and manufacturing companies demand equipment-specific depreciation considerations.</p><h3>Creative Collateral Structures</h3><p>When traditional collateral falls short, expert lenders leverage life insurance assignments, intellectual property valuations, franchise agreement value, and cross-collateralization strategies to strengthen loan structures while remaining within SBA guidelines.</p>', 2, true, 14, 'Expert Analysis', 'Explore advanced underwriting strategies for complex multi-entity SBA 7(a) transactions.'),

('sba-7(a)-module-3-expert', 'SBA 7(a) Secondary Market Strategies', '<h2>Maximizing Value Through Secondary Market Operations</h2><p>The SBA secondary market provides significant revenue opportunities for expert lenders who understand premium pricing, servicing retention, and market timing strategies.</p><h3>Premium Optimization</h3><p>SBA loan premiums fluctuate based on interest rates, market demand, and loan characteristics. Expert lenders understand how to structure loans for maximum premium value, including rate selection, maturity optimization, and borrower quality enhancement.</p><h3>Servicing Portfolio Management</h3><p>Retained servicing creates a recurring revenue stream that expert lenders manage strategically. This includes servicing transfer considerations, portfolio valuation, and the economics of retained vs. released servicing rights.</p><h3>Market Timing and Hedging</h3><p>Interest rate movements significantly impact secondary market premiums. Expert lenders develop hedging strategies and market timing approaches to protect premium income while managing pipeline risk.</p>', 3, true, 11, 'Expert Analysis', 'Learn secondary market strategies including premium optimization and servicing portfolio management.');

-- Expert-level articles for Commercial Real Estate track
INSERT INTO course_articles (module_id, title, content, order_index, is_published, reading_time_minutes, category, excerpt) VALUES
('commercial-real-estate-module-1-expert', 'Advanced CRE Loan Structuring', '<h2>Mastering Complex Commercial Real Estate Transactions</h2><p>Expert CRE lenders handle transactions that push beyond conventional lending parameters—mixed-use developments, ground-up construction with permanent financing, and portfolio refinancings that require sophisticated structuring.</p><h3>Participation and Syndication</h3><p>Large CRE transactions often exceed individual bank lending limits. Expert lenders understand participation structures, lead vs. participant roles, intercreditor agreements, and syndication economics that enable larger deals while managing concentration risk.</p><h3>CMBS and Capital Markets Alternatives</h3><p>Understanding when to refer borrowers to CMBS, life company, or agency execution is a hallmark of expert CRE lenders. Each capital source has distinct underwriting criteria, rate structures, and flexibility parameters that match different borrower needs.</p><h3>Distressed Asset Strategies</h3><p>Economic cycles create opportunities in distressed CRE assets. Expert lenders understand workout strategies, deed-in-lieu arrangements, loan modifications, and the legal frameworks governing troubled commercial real estate loans.</p>', 1, true, 13, 'Expert Analysis', 'Master complex CRE deal structuring including participation, syndication, and distressed asset strategies.'),

('commercial-real-estate-module-2-expert', 'Advanced CRE Valuation and Due Diligence', '<h2>Expert-Level Property Analysis and Risk Assessment</h2><p>Expert CRE lenders conduct due diligence that goes far beyond ordering an appraisal. This includes independent market analysis, tenant credit evaluation, environmental risk assessment, and forward-looking cash flow modeling.</p><h3>Discounted Cash Flow Modeling</h3><p>While basic lenders rely on direct capitalization, experts build DCF models that account for lease rollover risk, tenant improvement costs, capital expenditure reserves, and market rent growth assumptions to determine true property value under various scenarios.</p><h3>Environmental and Regulatory Risk</h3><p>Phase I and Phase II environmental assessments are just the starting point. Expert lenders evaluate zoning compliance, ADA requirements, building code issues, and emerging regulations like energy efficiency mandates that can materially impact property values.</p><h3>Tenant Credit Analysis</h3><p>In multi-tenant properties, expert lenders analyze individual tenant credit quality, lease terms, renewal probability, and replacement cost to assess the stability of the property''s income stream and identify concentration risks.</p>', 2, true, 15, 'Expert Analysis', 'Deep dive into expert CRE valuation techniques including DCF modeling and advanced due diligence.');

-- Case studies for SBA 7(a)
INSERT INTO case_studies (module_id, title, company, situation, challenge, solution, outcome, order_index, lessons_learned) VALUES
('sba-7(a)-module-1-beginner', 'First-Time Business Acquisition', 'Pacific Northwest Dental Group', 'A dentist with 10 years of clinical experience wanted to acquire an established dental practice with $1.2M in annual revenue and 4 operatories.', 'The buyer had excellent clinical experience but limited business ownership experience. The practice valuation exceeded typical multiples due to its prime location and established patient base.', 'Structured an SBA 7(a) loan for $950,000 with a 10-year term. Used the practice''s historical cash flow to demonstrate debt service coverage of 1.35x. Included a seller training period and non-compete agreement as loan conditions.', 'Loan closed successfully within 45 days. The new owner increased revenue by 15% in the first year through extended hours and adding a hygienist. Loan payments remained current with comfortable margin.', 1, '["Seller financing for a portion (10%) demonstrated buyer commitment", "Non-compete agreements protect going concern value", "Historical cash flow is the strongest predictor of repayment ability", "Transition planning reduces operational disruption risk"]'::jsonb),

('sba-7(a)-module-2-beginner', 'Working Capital for Seasonal Business', 'Mountain Resort Supply Co.', 'A seasonal outdoor recreation supply company needed $250,000 in working capital to purchase inventory ahead of their peak summer season, representing 60% of annual revenue.', 'Traditional banks were hesitant due to the highly seasonal nature of the business, with 70% of revenue concentrated in a 4-month window. The company had been profitable for 5 years but seasonal cash flow swings made conventional lending difficult.', 'Approved an SBA 7(a) working capital loan with a 7-year term and interest-only payments during off-peak months. Structured the repayment schedule to align with the company''s seasonal cash flow pattern.', 'The company purchased inventory at volume discounts, improving gross margins by 8%. Revenue grew 22% in the following season. The flexible repayment structure eliminated the cash flow stress that had constrained growth.', 2, '["Seasonal payment structures dramatically improve borrower success rates", "Volume purchasing power can offset interest costs", "5-year track record in seasonal businesses provides reliable pattern data", "Working capital loans for inventory should be sized to historical sales patterns"]'::jsonb),

('commercial-real-estate-module-1-beginner', 'Owner-Occupied Office Purchase', 'Greenfield Engineering Associates', 'A 15-person engineering firm had been leasing 5,000 sq ft of office space for $8,500/month. With lease renewal approaching at $10,200/month, they explored purchasing their own facility.', 'The firm found an ideal 6,500 sq ft property listed at $1.1M but lacked the 20-25% down payment required by conventional CRE lenders. Additionally, environmental concerns existed due to a former dry cleaning tenant.', 'Utilized SBA 504 financing: a first mortgage from a conventional lender (50%), a CDC second mortgage (40%), and only 10% borrower equity. Ordered a Phase I environmental assessment that cleared the property. Total monthly cost of ownership was $7,800.', 'The firm saved $2,400/month compared to the new lease rate while building equity. The additional 1,500 sq ft allowed them to hire 3 more engineers, growing revenue by 25%. The property appreciated 18% over 3 years.', 1, '["Owner-occupied properties qualify for more favorable SBA terms", "Monthly ownership costs are often less than market rent", "Environmental due diligence is essential but rarely disqualifying", "Additional space creates capacity for revenue growth"]'::jsonb);
