
-- Batch 4: Remaining beginner modules 2-7 for Working Capital, Invoice Factoring, MCA, Franchise, Healthcare, Restaurant, ABL, LOC
INSERT INTO course_assessments (module_id, title, assessment_type, order_index, passing_score, is_required, max_attempts, time_limit_minutes, questions) VALUES

-- Working Capital 2-7
('working-capital-module-2-beginner', 'Working Capital Products Quiz', 'quiz', 1, 80, true, 3, 15, '[
  {"question": "What is a revolving line of credit for working capital?", "type": "multiple-choice", "options": ["One-time loan", "Flexible credit that can be drawn and repaid repeatedly", "Equipment lease", "Real estate loan"], "correctAnswer": "Flexible credit that can be drawn and repaid repeatedly", "explanation": "Revolving lines allow borrowing, repaying, and re-borrowing up to a limit.", "points": 10, "difficulty": "easy"},
  {"question": "What is invoice financing?", "type": "multiple-choice", "options": ["Paying vendors early", "Borrowing against outstanding invoices as collateral", "Sending invoices electronically", "A type of insurance"], "correctAnswer": "Borrowing against outstanding invoices as collateral", "explanation": "Invoice financing uses outstanding receivables to secure immediate cash.", "points": 15, "difficulty": "medium"},
  {"question": "What is a term working capital loan?", "type": "multiple-choice", "options": ["Revolving credit", "Fixed lump sum repaid over a set schedule", "Equity investment", "Grant"], "correctAnswer": "Fixed lump sum repaid over a set schedule", "explanation": "Term loans provide a lump sum with fixed repayment, unlike revolving facilities.", "points": 10, "difficulty": "easy"},
  {"question": "What is trade credit?", "type": "multiple-choice", "options": ["Bank loan", "Supplier-extended payment terms (net 30/60/90)", "Credit card", "Government subsidy"], "correctAnswer": "Supplier-extended payment terms (net 30/60/90)", "explanation": "Trade credit allows businesses to purchase inventory and pay suppliers later.", "points": 15, "difficulty": "medium"}
]'::jsonb),

('working-capital-module-3-beginner', 'Working Capital Borrower Assessment Quiz', 'quiz', 1, 80, true, 3, 15, '[
  {"question": "What is the most critical metric for working capital lending?", "type": "multiple-choice", "options": ["Revenue growth", "Cash flow cycle and liquidity ratios", "Number of employees", "Years in business"], "correctAnswer": "Cash flow cycle and liquidity ratios", "explanation": "Cash flow patterns and liquidity determine ability to repay short-term obligations.", "points": 15, "difficulty": "medium"},
  {"question": "What is the quick ratio?", "type": "multiple-choice", "options": ["Current assets / current liabilities", "(Cash + receivables) / current liabilities", "Total assets / total debt", "Revenue / expenses"], "correctAnswer": "(Cash + receivables) / current liabilities", "explanation": "Quick ratio excludes inventory for a more conservative liquidity measure.", "points": 15, "difficulty": "medium"},
  {"question": "Why is seasonality important in working capital analysis?", "type": "multiple-choice", "options": ["It is not important", "Cash flow timing mismatches create borrowing needs", "It affects the interest rate", "It determines the loan term"], "correctAnswer": "Cash flow timing mismatches create borrowing needs", "explanation": "Seasonal businesses need working capital when expenses precede revenue.", "points": 10, "difficulty": "easy"},
  {"question": "What is accounts receivable aging?", "type": "multiple-choice", "options": ["When AR was created", "Report showing how long invoices have been outstanding", "Customer age demographics", "Collection agency report"], "correctAnswer": "Report showing how long invoices have been outstanding", "explanation": "AR aging tracks invoice age buckets (0-30, 31-60, 61-90, 90+ days).", "points": 10, "difficulty": "easy"}
]'::jsonb),

('working-capital-module-4-beginner', 'Working Capital Documentation Quiz', 'quiz', 1, 80, true, 3, 15, '[
  {"question": "What financial statements are needed for working capital loans?", "type": "multiple-choice", "options": ["Balance sheet only", "Income statement, balance sheet, cash flow statement, and AR/AP aging", "Tax returns only", "Bank statements only"], "correctAnswer": "Income statement, balance sheet, cash flow statement, and AR/AP aging", "explanation": "Comprehensive financials plus aging reports show cash flow health.", "points": 15, "difficulty": "medium"},
  {"question": "What is a borrowing base certificate?", "type": "multiple-choice", "options": ["Loan application", "Periodic report of eligible collateral supporting the credit facility", "Insurance certificate", "Business license"], "correctAnswer": "Periodic report of eligible collateral supporting the credit facility", "explanation": "Borrowing base certificates update available borrowing capacity based on current assets.", "points": 15, "difficulty": "medium"},
  {"question": "How often are bank statements typically required?", "type": "multiple-choice", "options": ["Annually", "3-6 months of recent statements", "Weekly", "Only at application"], "correctAnswer": "3-6 months of recent statements", "explanation": "Lenders review 3-6 months of bank statements to assess cash flow patterns.", "points": 10, "difficulty": "easy"},
  {"question": "What is a personal financial statement used for?", "type": "multiple-choice", "options": ["Tax filing", "Evaluating guarantor net worth and personal cash flow", "Insurance application", "Employee hiring"], "correctAnswer": "Evaluating guarantor net worth and personal cash flow", "explanation": "PFS shows the guarantor assets, liabilities, and ability to support the business.", "points": 10, "difficulty": "easy"}
]'::jsonb),

('working-capital-module-5-beginner', 'Working Capital Financial Analysis Quiz', 'quiz', 1, 80, true, 3, 15, '[
  {"question": "What is the operating cycle?", "type": "multiple-choice", "options": ["Fiscal year", "Time from purchasing inventory to collecting cash from sales", "Monthly billing cycle", "Annual audit period"], "correctAnswer": "Time from purchasing inventory to collecting cash from sales", "explanation": "The operating cycle measures how long capital is tied up in operations.", "points": 15, "difficulty": "medium"},
  {"question": "What is days sales outstanding (DSO)?", "type": "multiple-choice", "options": ["Sales volume per day", "Average number of days to collect payment after a sale", "Days until next sale", "Inventory turnover rate"], "correctAnswer": "Average number of days to collect payment after a sale", "explanation": "DSO measures collection efficiency - lower is better.", "points": 15, "difficulty": "medium"},
  {"question": "What is inventory turnover ratio?", "type": "multiple-choice", "options": ["Number of employees", "How many times inventory is sold and replaced in a period", "Warehouse capacity", "Product variety count"], "correctAnswer": "How many times inventory is sold and replaced in a period", "explanation": "Higher turnover means inventory moves quickly, reducing carrying costs.", "points": 10, "difficulty": "easy"},
  {"question": "What does negative working capital indicate?", "type": "multiple-choice", "options": ["Strong financial health", "Current liabilities exceed current assets - potential liquidity risk", "High profitability", "Rapid growth"], "correctAnswer": "Current liabilities exceed current assets - potential liquidity risk", "explanation": "Negative working capital may signal difficulty meeting short-term obligations.", "points": 10, "difficulty": "easy"}
]'::jsonb),

('working-capital-module-6-beginner', 'Working Capital Underwriting Quiz', 'quiz', 1, 80, true, 3, 15, '[
  {"question": "What is the primary repayment source for working capital loans?", "type": "multiple-choice", "options": ["Asset liquidation", "Conversion of current assets to cash through normal operations", "Personal savings", "Additional borrowing"], "correctAnswer": "Conversion of current assets to cash through normal operations", "explanation": "Working capital loans are repaid from the normal cash conversion cycle.", "points": 10, "difficulty": "easy"},
  {"question": "What is cash flow coverage analysis?", "type": "multiple-choice", "options": ["Bank balance review", "Assessing whether operating cash flow covers all debt obligations", "Credit score check", "Revenue projection"], "correctAnswer": "Assessing whether operating cash flow covers all debt obligations", "explanation": "Cash flow coverage ensures the business generates enough cash for all payments.", "points": 15, "difficulty": "medium"},
  {"question": "Why do lenders review accounts payable aging?", "type": "multiple-choice", "options": ["To count vendors", "To assess if the business is paying its obligations on time", "To calculate revenue", "For tax purposes"], "correctAnswer": "To assess if the business is paying its obligations on time", "explanation": "Slow-paying AP may indicate cash flow stress or pending vendor disputes.", "points": 15, "difficulty": "medium"},
  {"question": "What is a clean-up period for revolving lines?", "type": "multiple-choice", "options": ["Cleaning the office", "Period where the borrower must pay the line to zero", "Audit requirement", "Annual review"], "correctAnswer": "Period where the borrower must pay the line to zero", "explanation": "Clean-up periods (30-60 days annually) confirm the line is not being used as term financing.", "points": 10, "difficulty": "easy"}
]'::jsonb),

('working-capital-module-7-beginner', 'Working Capital Management Quiz', 'quiz', 1, 80, true, 3, 15, '[
  {"question": "What is cash management in working capital?", "type": "multiple-choice", "options": ["Counting money", "Optimizing cash inflows, outflows, and balances for efficiency", "Storing cash in a vault", "ATM operations"], "correctAnswer": "Optimizing cash inflows, outflows, and balances for efficiency", "explanation": "Cash management involves timing and managing cash flows to minimize borrowing needs.", "points": 10, "difficulty": "easy"},
  {"question": "What are early payment discounts (2/10 net 30)?", "type": "multiple-choice", "options": ["2% penalty for late payment", "2% discount if paid within 10 days, otherwise full in 30", "Two payment options", "Monthly pricing"], "correctAnswer": "2% discount if paid within 10 days, otherwise full in 30", "explanation": "This common term means a 2% discount for early payment, equivalent to ~36% annual savings.", "points": 15, "difficulty": "medium"},
  {"question": "What is a lockbox arrangement?", "type": "multiple-choice", "options": ["Safe deposit box", "Bank collects and processes customer payments to accelerate cash flow", "Security system", "Post office service"], "correctAnswer": "Bank collects and processes customer payments to accelerate cash flow", "explanation": "Lockbox services speed up payment collection and reduce float time.", "points": 15, "difficulty": "medium"},
  {"question": "When should a business consider working capital financing?", "type": "multiple-choice", "options": ["Never", "When growth, seasonality, or timing gaps create cash flow shortfalls", "Only when failing", "Every quarter automatically"], "correctAnswer": "When growth, seasonality, or timing gaps create cash flow shortfalls", "explanation": "Working capital financing bridges temporary gaps between cash inflows and outflows.", "points": 10, "difficulty": "easy"}
]'::jsonb),

-- Invoice Factoring Beginner 2-7
('invoice-factoring-module-2-beginner', 'Factoring Products Quiz', 'quiz', 1, 80, true, 3, 15, '[
  {"question": "What is spot factoring?", "type": "multiple-choice", "options": ["Long-term contract", "Factoring individual invoices without a long-term commitment", "Monthly service", "Annual agreement"], "correctAnswer": "Factoring individual invoices without a long-term commitment", "explanation": "Spot factoring allows businesses to factor select invoices as needed.", "points": 15, "difficulty": "medium"},
  {"question": "What is whole ledger factoring?", "type": "multiple-choice", "options": ["Single invoice sale", "Factoring all or most of a company accounts receivable", "Partial payment plan", "Inventory financing"], "correctAnswer": "Factoring all or most of a company accounts receivable", "explanation": "Whole ledger requires factoring the entire AR portfolio for lower rates.", "points": 15, "difficulty": "medium"},
  {"question": "What is notification factoring?", "type": "multiple-choice", "options": ["Email alerts", "Customers are notified to pay the factor directly", "Private agreement", "Text messaging service"], "correctAnswer": "Customers are notified to pay the factor directly", "explanation": "In notification factoring, customers are directed to pay the factor, not the business.", "points": 10, "difficulty": "easy"},
  {"question": "What is the typical factoring fee range?", "type": "multiple-choice", "options": ["0.5-1%", "1-5% per 30 days", "10-15%", "25-30%"], "correctAnswer": "1-5% per 30 days", "explanation": "Factoring fees typically range 1-5% of invoice value per 30-day period.", "points": 10, "difficulty": "easy"}
]'::jsonb),

('invoice-factoring-module-3-beginner', 'Factoring Eligibility Quiz', 'quiz', 1, 80, true, 3, 15, '[
  {"question": "Whose creditworthiness matters most in factoring?", "type": "multiple-choice", "options": ["The business applying", "The business customers (account debtors)", "The business bank", "The business owners personally"], "correctAnswer": "The business customers (account debtors)", "explanation": "Factors evaluate the creditworthiness of the customers who will pay the invoices.", "points": 15, "difficulty": "medium"},
  {"question": "What industries commonly use factoring?", "type": "multiple-choice", "options": ["Only retail", "Trucking, staffing, manufacturing, and professional services", "Only construction", "Only healthcare"], "correctAnswer": "Trucking, staffing, manufacturing, and professional services", "explanation": "B2B businesses with long payment terms benefit most from factoring.", "points": 10, "difficulty": "easy"},
  {"question": "Can startups use factoring?", "type": "multiple-choice", "options": ["No, only established businesses", "Yes, since approval is based on customer credit, not business history", "Only after 5 years", "Only with SBA backing"], "correctAnswer": "Yes, since approval is based on customer credit, not business history", "explanation": "Factoring is accessible to startups because the factor evaluates customer credit.", "points": 15, "difficulty": "medium"},
  {"question": "What makes an invoice ineligible for factoring?", "type": "multiple-choice", "options": ["Being from a large company", "Being past due, disputed, or from related parties", "Being in US dollars", "Being under $10,000"], "correctAnswer": "Being past due, disputed, or from related parties", "explanation": "Disputed, past-due, or related-party invoices carry too much collection risk.", "points": 10, "difficulty": "easy"}
]'::jsonb),

('invoice-factoring-module-4-beginner', 'Factoring Documentation Quiz', 'quiz', 1, 80, true, 3, 15, '[
  {"question": "What is a factoring agreement?", "type": "multiple-choice", "options": ["Purchase order", "Contract defining terms, fees, and obligations between business and factor", "Invoice template", "Insurance policy"], "correctAnswer": "Contract defining terms, fees, and obligations between business and factor", "explanation": "The factoring agreement governs the relationship including rates, reserves, and recourse.", "points": 10, "difficulty": "easy"},
  {"question": "What is a notice of assignment?", "type": "multiple-choice", "options": ["Job transfer letter", "Document informing customers that invoices are assigned to the factor", "Insurance notification", "Tax form"], "correctAnswer": "Document informing customers that invoices are assigned to the factor", "explanation": "The notice directs customers to make payments to the factor.", "points": 15, "difficulty": "medium"},
  {"question": "What is a schedule of accounts?", "type": "multiple-choice", "options": ["Bank account list", "Detailed listing of invoices submitted for factoring", "Payment calendar", "Chart of accounts"], "correctAnswer": "Detailed listing of invoices submitted for factoring", "explanation": "Each factoring batch includes a schedule listing the invoices being factored.", "points": 10, "difficulty": "easy"},
  {"question": "What verification does the factor perform?", "type": "multiple-choice", "options": ["Nothing", "Confirms invoices are valid and goods/services were delivered", "Only credit check", "Only background check"], "correctAnswer": "Confirms invoices are valid and goods/services were delivered", "explanation": "Factors verify that invoices represent legitimate, completed transactions.", "points": 15, "difficulty": "medium"}
]'::jsonb),

('invoice-factoring-module-5-beginner', 'Factoring Financial Analysis Quiz', 'quiz', 1, 80, true, 3, 15, '[
  {"question": "How do you calculate the effective annual cost of factoring?", "type": "multiple-choice", "options": ["Monthly fee × 12", "Factor fee / advance amount × (365 / days outstanding)", "Purchase price / invoice value", "Flat annual rate"], "correctAnswer": "Factor fee / advance amount × (365 / days outstanding)", "explanation": "Annualizing the cost reveals the true APR, which can be 20-40%+.", "points": 15, "difficulty": "hard"},
  {"question": "When is factoring more cost-effective than a bank loan?", "type": "multiple-choice", "options": ["Always", "When the business cannot qualify for traditional financing", "Never", "Only for large companies"], "correctAnswer": "When the business cannot qualify for traditional financing", "explanation": "Factoring may be worthwhile despite higher cost when bank financing is unavailable.", "points": 15, "difficulty": "medium"},
  {"question": "What is dilution in factoring?", "type": "multiple-choice", "options": ["Stock dilution", "Reduction in collectible invoice value from credits, disputes, or returns", "Water damage", "Fee negotiation"], "correctAnswer": "Reduction in collectible invoice value from credits, disputes, or returns", "explanation": "High dilution rates indicate the business frequently issues credits or has disputes.", "points": 10, "difficulty": "easy"},
  {"question": "What is the rebate in factoring?", "type": "multiple-choice", "options": ["Discount coupon", "Reserve amount returned to client after invoice is collected", "Tax refund", "Interest refund"], "correctAnswer": "Reserve amount returned to client after invoice is collected", "explanation": "After collection, the factor releases the reserve minus fees back to the client.", "points": 10, "difficulty": "easy"}
]'::jsonb),

('invoice-factoring-module-6-beginner', 'Factoring Underwriting Quiz', 'quiz', 1, 80, true, 3, 15, '[
  {"question": "What is concentration risk in factoring?", "type": "multiple-choice", "options": ["Too many invoices", "Over-reliance on a few customers for most receivables", "Geographic spread", "Industry focus"], "correctAnswer": "Over-reliance on a few customers for most receivables", "explanation": "If one major customer defaults, it significantly impacts the entire portfolio.", "points": 15, "difficulty": "medium"},
  {"question": "What is a credit limit in factoring?", "type": "multiple-choice", "options": ["Credit card limit", "Maximum amount the factor will advance against a single customer", "Total facility size", "Personal credit limit"], "correctAnswer": "Maximum amount the factor will advance against a single customer", "explanation": "Credit limits cap exposure to individual account debtors to manage concentration risk.", "points": 10, "difficulty": "easy"},
  {"question": "What does the factor check before advancing funds?", "type": "multiple-choice", "options": ["Weather forecast", "Customer credit, invoice validity, and lien searches", "Stock market", "Employee reviews"], "correctAnswer": "Customer credit, invoice validity, and lien searches", "explanation": "Due diligence includes customer creditworthiness, invoice verification, and UCC searches.", "points": 15, "difficulty": "medium"},
  {"question": "What is cross-aging in factoring?", "type": "multiple-choice", "options": ["Age diversity", "When one past-due invoice makes all invoices from that customer ineligible", "Credit score aging", "Account maturity"], "correctAnswer": "When one past-due invoice makes all invoices from that customer ineligible", "explanation": "Cross-aging excludes all invoices from a customer when any invoice exceeds aging limits.", "points": 10, "difficulty": "easy"}
]'::jsonb),

('invoice-factoring-module-7-beginner', 'Factoring Management Quiz', 'quiz', 1, 80, true, 3, 15, '[
  {"question": "What is a factoring reserve account?", "type": "multiple-choice", "options": ["Savings account", "Funds held by the factor as security against losses", "Emergency fund", "Tax escrow"], "correctAnswer": "Funds held by the factor as security against losses", "explanation": "Reserves protect the factor against dilution, disputes, and non-collection.", "points": 10, "difficulty": "easy"},
  {"question": "How does a factor handle chargebacks?", "type": "multiple-choice", "options": ["Ignores them", "Debits the client reserve or requires repurchase of uncollected invoices", "Files insurance", "Sues the customer"], "correctAnswer": "Debits the client reserve or requires repurchase of uncollected invoices", "explanation": "Under recourse factoring, uncollected invoices are charged back to the client.", "points": 15, "difficulty": "medium"},
  {"question": "What is termination notice in a factoring agreement?", "type": "multiple-choice", "options": ["Immediate exit", "Required notice period (30-90 days) to end the factoring relationship", "Employee termination", "Account closure"], "correctAnswer": "Required notice period (30-90 days) to end the factoring relationship", "explanation": "Most agreements require 30-90 days notice plus settlement of outstanding advances.", "points": 15, "difficulty": "medium"},
  {"question": "What happens to the reserve when factoring ends?", "type": "multiple-choice", "options": ["Factor keeps it", "Released to client after all invoices are collected or resolved", "Donated to charity", "Applied to future factoring"], "correctAnswer": "Released to client after all invoices are collected or resolved", "explanation": "The reserve is returned once all outstanding invoices are collected and obligations settled.", "points": 10, "difficulty": "easy"}
]'::jsonb);
