
-- Batch 2: Module 2-7 assessments for CRE, Construction, Equipment beginner + Expert Module 1s
INSERT INTO course_assessments (module_id, title, assessment_type, order_index, passing_score, is_required, max_attempts, time_limit_minutes, questions) VALUES

-- CRE Beginner Modules 2-7
('commercial-real-estate-module-2-beginner', 'CRE Property Types & Deal Structures Quiz', 'quiz', 1, 80, true, 3, 15, '[
  {"question": "What is a triple net (NNN) lease?", "type": "multiple-choice", "options": ["Tenant pays rent only", "Tenant pays rent plus taxes, insurance, and maintenance", "Landlord covers all expenses", "A short-term lease under 3 years"], "correctAnswer": "Tenant pays rent plus taxes, insurance, and maintenance", "explanation": "In NNN leases, tenants pay base rent plus property taxes, insurance, and maintenance.", "points": 15, "difficulty": "medium"},
  {"question": "What is a CMBS loan?", "type": "multiple-choice", "options": ["A government-backed mortgage", "A loan pooled and sold as mortgage-backed securities", "A construction-only loan", "A credit union commercial loan"], "correctAnswer": "A loan pooled and sold as mortgage-backed securities", "explanation": "CMBS loans are pooled into securities and sold to investors on the bond market.", "points": 15, "difficulty": "medium"},
  {"question": "What is a stabilized property?", "type": "multiple-choice", "options": ["A newly constructed building", "A property achieving consistent occupancy and cash flow", "A property with no debt", "A government-owned building"], "correctAnswer": "A property achieving consistent occupancy and cash flow", "explanation": "Stabilized properties have reached target occupancy and generate predictable NOI.", "points": 10, "difficulty": "easy"},
  {"question": "What is a bridge loan in CRE?", "type": "multiple-choice", "options": ["Long-term permanent financing", "Short-term financing until permanent financing or sale", "A loan for bridge construction", "An SBA program"], "correctAnswer": "Short-term financing until permanent financing or sale", "explanation": "Bridge loans provide interim financing, typically 6-36 months, until stabilization.", "points": 10, "difficulty": "easy"}
]'::jsonb),

('commercial-real-estate-module-3-beginner', 'CRE Borrower Assessment Quiz', 'quiz', 1, 80, true, 3, 15, '[
  {"question": "What is a sponsor in CRE lending?", "type": "multiple-choice", "options": ["The bank providing the loan", "The principal borrower or guarantor with experience", "The property manager", "The insurance company"], "correctAnswer": "The principal borrower or guarantor with experience", "explanation": "The sponsor is the key principal providing experience, net worth, and guarantees.", "points": 10, "difficulty": "easy"},
  {"question": "What is global cash flow analysis?", "type": "multiple-choice", "options": ["Analyzing only the subject property", "Evaluating all income sources of the borrower/guarantor", "International currency assessment", "Cash flow from multiple countries"], "correctAnswer": "Evaluating all income sources of the borrower/guarantor", "explanation": "Global cash flow considers all properties and income sources of the sponsor.", "points": 15, "difficulty": "medium"},
  {"question": "What minimum net worth ratio do CRE lenders typically require?", "type": "multiple-choice", "options": ["Net worth equal to 25% of loan", "Net worth equal to loan amount", "Net worth equal to property value", "No net worth requirement"], "correctAnswer": "Net worth equal to loan amount", "explanation": "Most CRE lenders require the sponsor net worth to equal or exceed the loan amount.", "points": 15, "difficulty": "medium"},
  {"question": "What is a rent roll?", "type": "multiple-choice", "options": ["Building maintenance schedule", "List of all tenants with lease terms and rental rates", "Property tax assessment", "Utility cost summary"], "correctAnswer": "List of all tenants with lease terms and rental rates", "explanation": "A rent roll details all tenants, lease expiration dates, square footage, and rental rates.", "points": 10, "difficulty": "easy"}
]'::jsonb),

('commercial-real-estate-module-4-beginner', 'CRE Documentation & Compliance Quiz', 'quiz', 1, 80, true, 3, 15, '[
  {"question": "What is a Phase I Environmental Site Assessment?", "type": "multiple-choice", "options": ["Soil testing for contaminants", "Historical review to identify potential contamination", "Water quality testing", "Air quality measurement"], "correctAnswer": "Historical review to identify potential contamination", "explanation": "Phase I is a historical records review; Phase II involves actual physical testing.", "points": 15, "difficulty": "medium"},
  {"question": "What is an ALTA survey?", "type": "multiple-choice", "options": ["Property insurance", "Detailed survey showing boundaries, easements, and improvements", "Tenant satisfaction survey", "Market rent analysis"], "correctAnswer": "Detailed survey showing boundaries, easements, and improvements", "explanation": "ALTA surveys provide comprehensive property boundary and encumbrance information.", "points": 15, "difficulty": "medium"},
  {"question": "What does zoning compliance verify?", "type": "multiple-choice", "options": ["Tenant creditworthiness", "That property use conforms to local zoning laws", "Building insurance coverage", "Loan-to-value ratio"], "correctAnswer": "That property use conforms to local zoning laws", "explanation": "Zoning compliance ensures the current and intended use is legally permitted.", "points": 10, "difficulty": "easy"},
  {"question": "What is title insurance?", "type": "multiple-choice", "options": ["Property damage insurance", "Protection against defects in property ownership", "Flood insurance", "Liability insurance"], "correctAnswer": "Protection against defects in property ownership", "explanation": "Title insurance protects against claims from title defects, liens, or encumbrances.", "points": 10, "difficulty": "easy"}
]'::jsonb),

('commercial-real-estate-module-5-beginner', 'CRE Financial Analysis Quiz', 'quiz', 1, 80, true, 3, 15, '[
  {"question": "What is the DSCR formula for CRE?", "type": "multiple-choice", "options": ["NOI / Annual debt service", "Gross rent / Mortgage payment", "Net income / Total liabilities", "Cash flow / Equity"], "correctAnswer": "NOI / Annual debt service", "explanation": "CRE DSCR = Net Operating Income / Annual debt service (P&I).", "points": 10, "difficulty": "easy"},
  {"question": "What is a typical minimum DSCR for CRE loans?", "type": "multiple-choice", "options": ["0.90x", "1.0x", "1.20-1.25x", "1.50x"], "correctAnswer": "1.20-1.25x", "explanation": "Most CRE lenders require minimum 1.20-1.25x DSCR.", "points": 15, "difficulty": "medium"},
  {"question": "What is vacancy and collection loss?", "type": "multiple-choice", "options": ["Insurance cost", "Estimated income loss from empty units and non-payment", "Property depreciation", "Marketing expenses"], "correctAnswer": "Estimated income loss from empty units and non-payment", "explanation": "Typically 5-10% is deducted from gross potential income for vacancies and credit losses.", "points": 15, "difficulty": "medium"},
  {"question": "What is a cash-on-cash return?", "type": "multiple-choice", "options": ["Total property value appreciation", "Annual pre-tax cash flow / Total cash invested", "NOI / Purchase price", "Gross rent multiplier"], "correctAnswer": "Annual pre-tax cash flow / Total cash invested", "explanation": "Cash-on-cash return measures the annual return on the actual equity invested.", "points": 10, "difficulty": "easy"}
]'::jsonb),

('commercial-real-estate-module-6-beginner', 'CRE Underwriting Fundamentals Quiz', 'quiz', 1, 80, true, 3, 15, '[
  {"question": "What is the debt yield in CRE underwriting?", "type": "multiple-choice", "options": ["Interest rate on the loan", "NOI / Total loan amount", "Cap rate minus vacancy", "Cash flow / Equity"], "correctAnswer": "NOI / Total loan amount", "explanation": "Debt yield = NOI / Loan amount, used to assess risk independent of cap rate and interest rate.", "points": 15, "difficulty": "medium"},
  {"question": "What is a stress test in CRE underwriting?", "type": "multiple-choice", "options": ["Physical building inspection", "Analyzing loan performance under adverse scenarios", "Tenant background check", "Environmental assessment"], "correctAnswer": "Analyzing loan performance under adverse scenarios", "explanation": "Stress tests model higher vacancy, rising rates, or declining rents to assess loan resilience.", "points": 15, "difficulty": "medium"},
  {"question": "What is the breakeven occupancy ratio?", "type": "multiple-choice", "options": ["Occupancy needed to cover all operating expenses and debt service", "Maximum allowed vacancy", "Tenant satisfaction threshold", "Minimum lease term"], "correctAnswer": "Occupancy needed to cover all operating expenses and debt service", "explanation": "Breakeven occupancy shows the minimum occupancy required to cover expenses and debt.", "points": 10, "difficulty": "easy"},
  {"question": "What role does the appraisal play in CRE underwriting?", "type": "multiple-choice", "options": ["Sets the interest rate", "Provides independent property valuation for LTV calculation", "Determines insurance cost", "Establishes zoning compliance"], "correctAnswer": "Provides independent property valuation for LTV calculation", "explanation": "The appraisal provides the market value used to calculate loan-to-value ratio.", "points": 10, "difficulty": "easy"}
]'::jsonb),

('commercial-real-estate-module-7-beginner', 'CRE Strategic Management Quiz', 'quiz', 1, 80, true, 3, 15, '[
  {"question": "What is loan maturity risk in CRE?", "type": "multiple-choice", "options": ["Risk of tenant default", "Risk that refinancing may not be available at maturity", "Risk of property damage", "Risk of interest rate decrease"], "correctAnswer": "Risk that refinancing may not be available at maturity", "explanation": "Maturity risk arises when market conditions or property performance prevent refinancing.", "points": 15, "difficulty": "medium"},
  {"question": "What is a loan modification?", "type": "multiple-choice", "options": ["A new loan application", "Changes to existing loan terms to prevent default", "Converting to a different property type", "Selling the property"], "correctAnswer": "Changes to existing loan terms to prevent default", "explanation": "Modifications may include rate adjustments, term extensions, or payment deferrals.", "points": 10, "difficulty": "easy"},
  {"question": "What is a deficiency judgment?", "type": "multiple-choice", "options": ["Building code violation", "Legal claim for remaining balance after foreclosure sale", "Tenant eviction order", "Insurance claim"], "correctAnswer": "Legal claim for remaining balance after foreclosure sale", "explanation": "If foreclosure proceeds do not cover the loan balance, the lender may pursue a deficiency judgment.", "points": 15, "difficulty": "hard"},
  {"question": "What is portfolio diversification in CRE lending?", "type": "multiple-choice", "options": ["Owning one large property", "Spreading risk across property types, locations, and tenants", "Having multiple loans at one bank", "Investing only in office buildings"], "correctAnswer": "Spreading risk across property types, locations, and tenants", "explanation": "Diversification reduces concentration risk by varying asset types and geographies.", "points": 10, "difficulty": "easy"}
]'::jsonb),

-- Expert Module 1s for all major course types
('sba-7(a)-module-1-expert', 'Advanced SBA 7(a) Market Strategy Quiz', 'quiz', 1, 85, true, 3, 20, '[
  {"question": "What is the SBA Preferred Lender Program (PLP)?", "type": "multiple-choice", "options": ["A borrower reward program", "Delegated authority for experienced lenders to approve loans", "A secondary market program", "SBA direct lending"], "correctAnswer": "Delegated authority for experienced lenders to approve loans", "explanation": "PLP lenders have delegated authority to make credit decisions without prior SBA approval.", "points": 15, "difficulty": "medium"},
  {"question": "What is the SBA secondary market?", "type": "multiple-choice", "options": ["Backup lending source", "Market where guaranteed portions of 7(a) loans are sold", "Federal Reserve lending window", "State-level loan guarantee program"], "correctAnswer": "Market where guaranteed portions of 7(a) loans are sold", "explanation": "Lenders can sell the guaranteed portion to provide liquidity and generate premium income.", "points": 20, "difficulty": "hard"},
  {"question": "What premium can lenders earn selling 7(a) guaranteed portions?", "type": "multiple-choice", "options": ["0-2%", "5-12%", "15-20%", "25-30%"], "correctAnswer": "5-12%", "explanation": "Secondary market premiums typically range 5-12% depending on rate, maturity, and market conditions.", "points": 20, "difficulty": "hard"},
  {"question": "What is the SBA CARES Act impact on 7(a) lending?", "type": "multiple-choice", "options": ["Eliminated the program", "Temporarily enhanced guarantee percentages and fee waivers", "Reduced maximum loan amounts", "Made all businesses eligible"], "correctAnswer": "Temporarily enhanced guarantee percentages and fee waivers", "explanation": "CARES Act temporarily provided 90% guarantees and waived borrower/lender fees.", "points": 15, "difficulty": "medium"}
]'::jsonb),

('sba-504-module-1-expert', 'Advanced SBA 504 Strategy Quiz', 'quiz', 1, 85, true, 3, 20, '[
  {"question": "How are 504 debentures funded?", "type": "multiple-choice", "options": ["Direct SBA appropriation", "Sold as pooled securities in the capital markets", "From bank deposits", "Through FDIC insurance fund"], "correctAnswer": "Sold as pooled securities in the capital markets", "explanation": "504 debentures are pooled monthly and sold as government-guaranteed securities.", "points": 20, "difficulty": "hard"},
  {"question": "What is the 504 refinance program requirement?", "type": "multiple-choice", "options": ["No equity required", "Borrower must have been current for 12 months", "Only available for new construction", "Restricted to manufacturing"], "correctAnswer": "Borrower must have been current for 12 months", "explanation": "504 refinance requires the existing loan to have been current for at least 12 months.", "points": 15, "difficulty": "medium"},
  {"question": "What is the job creation requirement for 504?", "type": "multiple-choice", "options": ["No jobs required", "1 job per $65,000 of CDC debenture", "10 jobs minimum", "5% of workforce growth"], "correctAnswer": "1 job per $65,000 of CDC debenture", "explanation": "504 requires creating or retaining 1 job per $65,000 of CDC debenture (higher for small manufacturers).", "points": 20, "difficulty": "hard"},
  {"question": "What advantage does 504 offer over conventional CRE?", "type": "multiple-choice", "options": ["No down payment", "Below-market fixed rate on CDC portion for 20-25 years", "No personal guarantees", "100% financing"], "correctAnswer": "Below-market fixed rate on CDC portion for 20-25 years", "explanation": "The CDC debenture carries a below-market fixed rate for the full term, reducing interest rate risk.", "points": 15, "difficulty": "medium"}
]'::jsonb),

('commercial-real-estate-module-1-expert', 'Advanced CRE Market Analysis Quiz', 'quiz', 1, 85, true, 3, 20, '[
  {"question": "What is a going-in cap rate vs exit cap rate?", "type": "multiple-choice", "options": ["They are the same thing", "Going-in is at acquisition; exit is projected at sale", "Going-in is for new construction; exit is for existing", "Going-in includes debt; exit excludes debt"], "correctAnswer": "Going-in is at acquisition; exit is projected at sale", "explanation": "Going-in cap rate values the property at purchase; exit cap rate projects value at disposition.", "points": 20, "difficulty": "hard"},
  {"question": "What is IRR in CRE investment analysis?", "type": "multiple-choice", "options": ["Insurance Risk Rating", "Internal Rate of Return - discount rate making NPV zero", "Institutional Regulatory Requirement", "Interest Rate Reset"], "correctAnswer": "Internal Rate of Return - discount rate making NPV zero", "explanation": "IRR is the discount rate at which the net present value of all cash flows equals zero.", "points": 20, "difficulty": "hard"},
  {"question": "What is absorption rate in CRE?", "type": "multiple-choice", "options": ["Speed of loan payoff", "Rate at which available space is leased over time", "Construction completion percentage", "Tenant turnover rate"], "correctAnswer": "Rate at which available space is leased over time", "explanation": "Absorption rate measures market demand by tracking how quickly vacant space is leased.", "points": 15, "difficulty": "medium"},
  {"question": "What is a highest and best use analysis?", "type": "multiple-choice", "options": ["Finding the cheapest use", "Determining the most profitable legally permissible use", "Zoning classification", "Building code requirement"], "correctAnswer": "Determining the most profitable legally permissible use", "explanation": "Highest and best use considers legal, physical, financial, and maximally productive criteria.", "points": 15, "difficulty": "medium"}
]'::jsonb),

('construction-loans-module-1-expert', 'Advanced Construction Lending Quiz', 'quiz', 1, 85, true, 3, 20, '[
  {"question": "What is a guaranteed maximum price (GMP) contract?", "type": "multiple-choice", "options": ["Lender guarantee on rate", "Contractor caps total cost with savings shared", "Government construction subsidy", "Insurance premium cap"], "correctAnswer": "Contractor caps total cost with savings shared", "explanation": "GMP contracts cap the construction cost, with savings typically shared between owner and contractor.", "points": 15, "difficulty": "medium"},
  {"question": "What is retainage in construction lending?", "type": "multiple-choice", "options": ["Loan reserve", "Percentage withheld from contractor payments until completion", "Builder insurance", "Permit deposit"], "correctAnswer": "Percentage withheld from contractor payments until completion", "explanation": "Retainage (typically 10%) is withheld from each draw to ensure contractor performance.", "points": 15, "difficulty": "medium"},
  {"question": "What is a soft cost vs hard cost?", "type": "multiple-choice", "options": ["Soft costs are optional; hard costs are mandatory", "Hard costs are physical construction; soft costs are design, permits, financing", "They are the same", "Soft costs are variable; hard costs are fixed"], "correctAnswer": "Hard costs are physical construction; soft costs are design, permits, financing", "explanation": "Hard costs = direct construction. Soft costs = architecture, engineering, permits, fees, financing costs.", "points": 20, "difficulty": "hard"},
  {"question": "What is the loan-to-cost vs loan-to-value distinction?", "type": "multiple-choice", "options": ["They measure the same thing", "LTC uses total development cost; LTV uses completed market value", "LTC is for residential; LTV for commercial", "LTV is always higher than LTC"], "correctAnswer": "LTC uses total development cost; LTV uses completed market value", "explanation": "LTC = loan / total costs. LTV = loan / projected completed value. LTV is usually lower if value exceeds cost.", "points": 20, "difficulty": "hard"}
]'::jsonb),

('equipment-financing-module-1-expert', 'Advanced Equipment Finance Strategy Quiz', 'quiz', 1, 85, true, 3, 20, '[
  {"question": "What is the difference between a capital lease and an operating lease under ASC 842?", "type": "multiple-choice", "options": ["No difference under new rules", "Capital leases transfer ownership risk; operating leases do not", "Operating leases are always shorter", "Capital leases are for used equipment only"], "correctAnswer": "Capital leases transfer ownership risk; operating leases do not", "explanation": "Under ASC 842, finance (capital) leases transfer substantially all risks and rewards of ownership.", "points": 20, "difficulty": "hard"},
  {"question": "What is residual value risk in equipment finance?", "type": "multiple-choice", "options": ["Risk of equipment malfunction", "Risk that equipment value at end of term is less than projected", "Insurance cost increases", "Regulatory compliance risk"], "correctAnswer": "Risk that equipment value at end of term is less than projected", "explanation": "Residual value risk affects lease pricing and the lender recovery potential.", "points": 15, "difficulty": "medium"},
  {"question": "What is Section 179 deduction for equipment?", "type": "multiple-choice", "options": ["Insurance deduction", "Immediate expensing of qualifying equipment purchases", "Interest rate reduction", "Sales tax exemption"], "correctAnswer": "Immediate expensing of qualifying equipment purchases", "explanation": "Section 179 allows businesses to immediately deduct the full purchase price of qualifying equipment.", "points": 15, "difficulty": "medium"},
  {"question": "What is a sale-leaseback in equipment finance?", "type": "multiple-choice", "options": ["Selling old equipment", "Selling owned equipment to a lessor and leasing it back", "A warranty program", "Trading equipment for newer models"], "correctAnswer": "Selling owned equipment to a lessor and leasing it back", "explanation": "Sale-leasebacks convert owned equipment equity into cash while retaining use of the asset.", "points": 20, "difficulty": "hard"}
]'::jsonb);
